### ISSUE TITLE
[BUG] Setup dialog off screen

### ISSUE THREAD

**Issue by jpotelle** [clechasseur/pathcopycopy#101]
**Describe the bug**
When invoking "setup" from the submenu, the dialog appears off screen. To fix, I had to regedit the saved X/Y positions to 0/0.

**Expected behavior**
The dialog should check that it's screen position falls within the current display boundaries and reset X/Y to 0/0 if necessary.

**Software (please complete the following information):**
 - OS: Windows 10 Pro
 - Path Copy Copy Version 17.1

Thanks!

**Comment by clechasseur** [comment]
Just to be sure, I assume this is because you moved the dialog to a position on another monitor, then disconnected the monitor?

**Comment by jpotelle** [comment]
No, I exported settings from one computer and imported them on another computer that has a completely different video setup... 
--

**Comment by clechasseur** [comment]
Interesting use case. It's a bug that needs to be fixed for sure.

**Comment by clechasseur** [comment]
This bug has been fixed and will be part of the next major release (tentatively 18.0).
