### ISSUE TITLE
[BUG] 18.0 reported as virus Trojan:Win32/Detplock

### ISSUE THREAD

**Issue by gemal** [clechasseur/pathcopycopy#102]
![image](https://user-images.githubusercontent.com/69105/73159331-93876080-40e6-11ea-9462-af49c8e4842e.png)

**Comment by syldub69** [comment]
Same issue encountered.

**Comment by clechasseur** [comment]
We see false positive detections almost every release.

I uploaded the installer to VirusTotal:

https://www.virustotal.com/gui/file/1e0d4ca669be817b4033cae0ccf1cc7d733d629d05a3a78a428eb741a93ef7f6/detection

One antivirus (BitDefender) reports a problem; others are all green.

There's not much I can do about those, unfortunately. You will need to bypass your antivirus to install.
