### ISSUE TITLE
[SUGGESTION] Update web page for Windows Vista requirement

### ISSUE THREAD

**Issue by goozak** [clechasseur/pathcopycopy#103]
The [web page](https://pathcopycopy.github.io/) mentions "Path Copy Copy works on Windows XP or later."  ;-)

**Comment by clechasseur** [comment]
Yeah, I knew I had to do this, but procrastination made a good case. ;-)

**Comment by pathcopycopy** [comment]
Fixed in the README.md as well as the Path Copy Copy site.
