### ISSUE TITLE
Pathcopycopy release 18.0 will not allow me to accept license terms and install 

### ISSUE THREAD

**Issue by pabristow** [clechasseur/pathcopycopy#105]
**Describe the bug**

Pathcopycopy release 18.0 will not allow me to accept license terms and install.

Windows 10, having version 17.1 installed OK.

Cancel button does not cancel, but closing window via X 
**To Reproduce**
1. Go to location of pathcopycopy18.0.exe
2. Click on pathcopycopy18.0.exe

3. Try to accept the license terms, but cannot get the button to light.
4. Click on cancel - nothing happens.
5 Click on X, exists setup with a message to confirm.

**Expected behavior**
install

**Software (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Path Copy Copy Version [e.g. 18.0]

**Additional context**

 version 17.1 installed OK.

**Comment by clechasseur** [comment]
Strange. Did you get to choose between All Users and Current User installation modes before getting to the license page?

If the answer is no, can you try to uninstall your current version and then try to install 18.0? (You won't lose your settings if you uninstall.)

**Comment by pabristow** [comment]
Strange indeed, but the good news is that pathcopycopy 18.0 installed as expected after a cold start this morning.

I've checked my version and that it works OK too.

(The install failure may be connected with an strange Outlook behaviour unable to read any downloaded messages, also 'fixed' by a cold start).

So I blame Windows 10 for this.  Sorry for noise.  (And thanks again for an excellent applet - should be standard Windows!)
