### ISSUE TITLE
[FEATURE] French translation

### ISSUE THREAD

**Issue by RotorStator** [clechasseur/pathcopycopy#107]
Hello,

Can you add a complete french translation for menus and settings window please ?
If you cant do that may'be I can do it if you give me the complete text to be translated.
Thank you very much.

**Comment by clechasseur** [comment]
Idée intéressante, surtout que je suis francophone moi-même. Je vais cependant devoir vérifier comment faire cela de manière générique.

**Comment by n0f4c3** [comment]
moi aussi je veux une traduction en Français en espérant que vous trouviez comment faire la traduction

**Comment by RotorStator** [comment]
Merci Charles. J'espère que vous réussirez.

**Comment by clechasseur** [comment]
French translation is ready and will be available in the next version. For those that want to take a look now, you can install the CI build: https://github.com/clechasseur/pathcopycopy/suites/942996646/artifacts/11683406

**Comment by RotorStator** [comment]
Thank you so much. I have donwloaded the file but I have to wait : Avast dont let me install it before they scan it. First time i see this.


![avast](https://user-images.githubusercontent.com/60708445/88079100-891dbf00-cb7d-11ea-93bc-97c3f9b86622.jpg)

**Comment by RotorStator** [comment]
J'ai désactivé Avast et j'ai pu faire l'installation qui bien sûr doit se faire en mode administrateur sinon elle échoue.
Merci infiniment Charles, ça fonctionne parfaitement et en français c'est bien plus pratique pour moi.
![17210455-sourire-caractère-jaune-donnant-un-coup-de-pouce](https://user-images.githubusercontent.com/60708445/88081630-f67f1f00-cb80-11ea-927b-e565b9627f3c.jpg)

**Comment by clechasseur** [comment]
> Thank you so much. I have donwloaded the file but I have to wait : Avast dont let me install it before they scan it. First time i see this.

That's because the CI builds are not signed executables... Official builds probably wouldn't have done that.

**Comment by RotorStator** [comment]
Et le verdict d'Avast ce matin (heureusement que je ne les ai pas attendus, ils m'avaient dit une trentaine d'heures pour contrôler ! ) :
![fichier sain](https://user-images.githubusercontent.com/60708445/88140105-60371180-cbf1-11ea-80b0-08a632eaa67f.jpg)
