### ISSUE TITLE
[FEATURE] Include Labels Into Copied Drives' Paths

### ISSUE THREAD

**Issue by Jack1789** [clechasseur/pathcopycopy#108]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Well, recently I'd been dealing with the backup of certain drives and I'm using their labels as names for the destination folders, thus I thought it would be handy to have your program copy the whole name, instead just their "single letter" paths.

For example:

"**`D:\`**" > "**D:\My Backup Drive 1**"
"**`G:\`**" > "**G:\Backup 2020 - Music**"

I know this might be slightly out of scope for what this program does, but I think considering a completely new program which does just that or some scripts related workaround, will be a last resort measure.

Thanks.

**Comment by Jack1789** [comment]
@clechasseur 

So? Do you think the above would be feasible?

Thanks.

**Comment by clechasseur** [comment]
I think it's feasible and I think it's in the scope of what the program does. I don't know how to do it yet, however - admittedly, I haven't looked into it. It would probably require the use of a different API to fetch the drive name.

My life has been pretty hectic these days and I've had less time to work on this, but I intend to look into it.

**Comment by Jack1789** [comment]
I see, well it's good t know what you think about it and that it is indeed doable. : )

I'm sure may it calmer days come to your life, that feature would be added.

Thanks.

**Comment by clechasseur** [comment]
This feature has been implemented as an expert-only custom command element. It will be available in the next version.

**Comment by Jack1789** [comment]
> This feature has been implemented as an expert-only custom command element. It will be available in the next version.

Hello, I have tried to use this feature, but it won't work. Would you please tell me the exact command to use?
Thanks.

**Comment by clechasseur** [comment]
> Hello, I have tried to use this feature, but it won't work. Would you please tell me the exact command to use? Thanks.

The custom command element to use is named "Inject Drive Label". It replaces any instance of the string %DRIVELABEL% in the path with the drive's label.

Here's a sample custom command that uses it:

[InjectDriveLabel.zip](https://github.com/clechasseur/pathcopycopy/files/10328218/InjectDriveLabel.zip)

**Comment by Jack1789** [comment]
> > Hello, I have tried to use this feature, but it won't work. Would you please tell me the exact command to use? Thanks.
> 
> The custom command element to use is named "Inject Drive Label"...

Hello, that one worked great! I was missing the "find / replace" part.

By the way, I leave you a little feature request, you might find useful to implement:

Making the PCC's "settings" window puts "always on top", since it get kind of difficult to locate it each time, when
there are other windows already opened. It doesn't show up on the taskbar, so I have to either go and close each of the remnant windows, one by one, till I spot the PCC's, or rather, I have to use the "show desktop" feature, to close them all at once, and then open at least other window in order the PCC's shows up as well.

Thanks.

**Comment by clechasseur** [comment]
> Making the PCC's "settings" window puts "always on top", since it get kind of difficult to locate it each time, when
there are other windows already opened. It doesn't show up on the taskbar, so I have to either go and close each of the remnant windows, one by one, till I spot the PCC's, or rather, I have to use the "show desktop" feature, to close them all at once, and then open at least other window in order the PCC's shows up as well.

I think there are two ways to solve this problem:

1. Make the Settings window "always-on-top"
2. Have the Settings window show up in the taskbar

Personally, I'd prefer number 2, but maybe that's just me. What do you think?

**Comment by Jack1789** [comment]
In case you want to implement only one, I would say number 2, since a window's title will be easily visible most times.
The "always-on-top" option would still be handy, in case there are already many opened windows in the taskbar, and it might suppose a little more effort to spot the exact one, since their titles will become shorter. But even in that kind of cases, a taskbar window with a well visible icon, should be enough.

**Comment by clechasseur** [comment]
![why-not-both-why-not](https://user-images.githubusercontent.com/1435551/210682072-29de4c20-dc6c-42a2-bc9d-bf6a9a42a828.gif)

I'll enter a task for each suggestion.
