### ISSUE TITLE
[BUG] Context menu options not showing up in Windows 7

### ISSUE THREAD

**Issue by bwinsto2** [clechasseur/pathcopycopy#109]
Using Windows 7; I installed the program, but when right-clicking on files, the options are the same as they were before installing the program. I don't see any new path copy options. Strangely, I decided to download this because I can't use the normal way to copy paths (i.e. hold down shift and right click) because that doesn't cause my computer to change the context menu either... Maybe something is messed up with my Windows? This is so weird and frustrating.

**Comment by clechasseur** [comment]
Good question. Did you install the program globally or for the current user only? Did you install the latest version (18.0)? Did you install any other contextual menu add-ons that work successfully?

**Comment by bwinsto2** [comment]
I installed it globally and I installed the current version. I haven't installed any other context menu add-ons as far as I know.

**Comment by clechasseur** [comment]
Ok, let's validate a few things first.

Can you open regedit and make sure the following keys exist:
- HKEY_CLASSES_ROOT\CLSID\{82CB99A2-2F18-4D5D-9476-54347E3B6720}
- HKEY_CLASSES_ROOT\*\shellex\ContextMenuHandlers\PathCopyCopy

Can you try to open a command prompt (cmd.exe) and execute the following:
```
rundll32 "C:\Program Files\Path Copy Copy\PCC64.dll",GetPathWithPlugin {3A42B5C6-72D6-4a8a-BA44-014FA64AA11A},C:\Windows\Notepad.exe
```
If that works, you should end up with "notepad.exe" in your clipboard.

**Comment by clechasseur** [comment]
No answer after a while, closing this.
