### ISSUE TITLE
[BUG] Double escape of space

### ISSUE THREAD

**Issue by kuty** [clechasseur/pathcopycopy#111]
**Describe the bug**
If path include space, it is escaped as %2520 instead of %20 as it was before. %25 is escape for char %, so it looks like it is escaped twice.

**Software (please complete the following information):**
 - OS: Windows 10

**Comment by clechasseur** [comment]
Is it possible that you selected the encoding option both in the global settings AND in a custom command? That would explain the double encoding.

**Comment by clechasseur** [comment]
I can only reproduce this by selecting the encoding option both in global and in the custom command. No further info so I'm closing this.
