### ISSUE TITLE
[BUG] Not All Filenames Get Copied With A Custom Command

### ISSUE THREAD

**Issue by Jack1789** [clechasseur/pathcopycopy#113]
**Describe the bug**

Trying to copy more than "16" filenames with a slightly modified version of the "Copy Long Name" command, from the "Main menu", will result in "nothing" being copied. In order to copy anything greater than such amount, the command must be invoked from the PCC's "Submenu" option.

**To Reproduce**

**1.** Create a new custom command, using the "Copy Long Name" command as base and the "Remove File Extension" option.
**2.** Select more than "16" files.
**3.** Use the newly created command.
**4.** Try to paste the clipboard's content.

**Expected behavior**

I would like that said command be able to copy more than "16" filenames at once, without having to obligatorily use it from the "Submenu".

**Screenshots**
.

**Software (please complete the following information):**
 - OS: Windows 8.1 Pro
 - Path Copy Copy v18.0

**Additional context**
.

**Comment by clechasseur** [comment]
Sounds like this is an old bug rearing its ugly head again ([see here](https://github.com/clechasseur/pathcopycopy/blob/ee65bf866a94f22439a7612cec2bbcf118ea41e6/HISTORY#L161))... So it works when the custom command is in the submenu, but not when it's in the main menu? That's pretty weird. I'll look into it.

**Comment by Jack1789** [comment]
Exactly.
It's really weird since another custom command I have works fine from the main menu.

**Comment by clechasseur** [comment]
I cannot reproduce this using the provided steps. Could you try exporting your custom command and including it here? Maybe there's something else that's causing this...

**Comment by Jack1789** [comment]
Hi, sorry for my belated reply, I just read the notification. Here I leave it you:

`<?xml version="1.0" encoding="utf-8"?><PipelinePluginCollection xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://pathcopycopy.codeplex.com/xsd/PipelinePlugins/V1"><Plugins><PipelinePluginInfo><Id>{6137537f-60d2-440f-ada7-8c8827b494b9}</Id><Description>FULL SIN EXT</Description><Pipeline>02{{3a42b5c6-72d6-4a8a-ba44-014fa64aa11a}.</Pipeline><EditMode>Simple</EditMode><Global>false</Global><RequiredVersion>17.0.0.0</RequiredVersion></PipelinePluginInfo></Plugins></PipelinePluginCollection>`

Regards.

**Comment by clechasseur** [comment]
Even after a long hiatus, I still cannot reproduce this, even with your provided command.

If you're still here, can you tell me where you're selecting the files exactly? A screenshot might help. Perhaps the contextual menu has to be invoked in a specific way...

**Comment by Jack1789** [comment]
> Even...

Hello, now I'm not anymore using Windows 8 as a my main system but I just tried to reproduce the bug on another Windows 8 system I have around and I couldn't, so I bet it had to do with something very specific from that old installation only.

Regards.
