### ISSUE TITLE
[FEATURE] "Duplicate" button for Custom Commands

### ISSUE THREAD

**Issue by jpotelle** [clechasseur/pathcopycopy#114]
**Describe the solution you'd like**
In the custom commands interface, a DUPLICATE button that will duplicate an existing custom command under a new name. Then I can edit the new command, which may contain, e.g. complex regex steps, etc. that I don't need to recreate by memory.

**Describe alternatives you've considered**
I've tried exporting and re-importing a custom command but that just overwrites it.

Thanks!

**Comment by clechasseur** [comment]
This feature has been implemented and will be shipped in the next version.
