### ISSUE TITLE
[FEATURE] Support for custom prefixes for WSL paths

### ISSUE THREAD

**Issue by iliazlobin** [clechasseur/pathcopycopy#117]
Currently, when you choose "Copy WSL" option, the "/mnt" prefix is added to the full path. Sometimes, users prefer having folders mounted to the root location (or others but `/mnt`). The `/etc/wsl.conf` file lets to [control this behaviour](https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/):
```conf
[automount]
enabled = true
root = /
```
Having this set, the copied path would have the wrong value:
* `/mnt/c/path/to/my/file` instead of `/c/path/to/my/file`

I found where it's hardcoded [in one of the project's source code files](https://github.com/clechasseur/pathcopycopy/blob/master/PathCopyCopy/plugins/src/WSLPathPlugin.cpp#L33), and have managed to edit it and recompile it for myself so that I have a correct path.

However, I believe, that this has to be configurable. Enabling a custom text field in settings (with a default value of `/mnt`) would be the best option for everybody.

**Comment by clechasseur** [comment]
I agree that it could be configurable. But in your case, isn't this exactly what the MSYS Path command does?

**Comment by clechasseur** [comment]
I've added a hidden setting to configure this. In the `HKEY_CURRENT_USER\Software\clechasseur\PathCopyCopy` registry key, setting the `WSLPathPrefix` value will override the default `/mnt`.

This will be available in the next version.
