### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by everweb** [clechasseur/pathcopycopy#120]
PathCopyCopyCOMPluginExecutor\prihdr is missing the file, "PathCopyCopy_i.h"

**Comment by everweb** [comment]
It maps to PathCopyCopy\generated\PathCopyCopy_i.h but there's nothing there - what's the generator ?

**Comment by clechasseur** [comment]
I'm not on my PC right now, but IIRC this is generated from the MIDL file in the PathCopyCopy project itself. So you need to build PathCopyCopy THEN the COMPluginExecutor. (The project and solution files are configured for this to happen.)

**Comment by clechasseur** [comment]
Confirmed: PathCopyCopy_i.h is built by MIDL from the following file:

PathCopyCopy\src\PathCopyCopy.idl

I can also confirm that the PathCopyCopy project is a dependency for PathCopyCopyCOMPluginExecutor, so it should always build first.
