### ISSUE TITLE
Suggestion: allow passing command-line arguments to executables

### ISSUE THREAD

**Issue by TedBax** [clechasseur/pathcopycopy#122]
(I'm very sorry, my english is terrible)

Launch executable with path(s) instead of copying to the clipboard
   ...and save paths in a filelist instead of passing them directly
      Executable:  C:\mytest.exe   (not possible to add parameters for mytest.exe)

Please, can you change your wonderfull tool:
Executable:  C:\mytest.exe
to:  Commandline:    C:\mytest.exe -mypar aaa -myflag %LISTFILE% -mypar bbb ...
%LISTFILE% is only a suggestion.

**Comment by clechasseur** [comment]
I assume the suggestion is to allow the user to pass command-line arguments and not to actually rename _Executable_ to _Command-line_?

**Comment by TedBax** [comment]
(now google translater)

Exactly, I would like to be able to pass further parameters to the startet exe. 

If you could make this possible, you would have to change "Executable" to "Commandline", because it is a real commandline, I think.
But of course the name is not so important to me :)

**Comment by clechasseur** [comment]
This has been implemented and will ship in the next version.
