### ISSUE TITLE
[BUG] Missing PCC in context-menu for shortcuts (x.LNK)

### ISSUE THREAD

**Issue by TedBax** [clechasseur/pathcopycopy#123]
checked:  Copy paths of shortcut (.lnk) files themselves
But after rightclick to an shortcut, there is not the menu-item 'Path Copy'.
Without unchecked LNK-option, there exist the menu-item 'Path Copy'.

A little suggestion please:
can you make a copy from the LNK-option in the global options to the options for a single Custom Command? Then it would possible to set the LNK-option for each Custom Command separately.

(sorry for real bad english)

**Comment by clechasseur** [comment]
> checked: Copy paths of shortcut (.lnk) files themselves
> But after rightclick to an shortcut, there is not the menu-item 'Path Copy'.
> Without unchecked LNK-option, there exist the menu-item 'Path Copy'.

Just to be certain: when you select that option, the Path Copy Copy menu item actually *moves* in the contextual menu. Is it possible you just missed it? (Sorry if this is obvious, I'm just trying to eliminate easy answers)

> A little suggestion please:
> can you make a copy from the LNK-option in the global options to the options for a single Custom Command? Then it would possible to set the LNK-option for each Custom Command separately.

Unfortunately, that's not possible. The technique to copy the path of .lnk files themselves is a little convoluted and must absolutely apply to the entire contextual menu extension. It is not possible to have it per-command.

> (sorry for real bad english)

Just in case that french is your main language: that's the case for me too, so if speaking french is easier for you, that works too. 😄

**Comment by TedBax** [comment]
Thank you very much for your answer.

_Just to be certain: when you select that option, the Path Copy Copy menu item actually moves in the contextual menu. Is it possible you just missed it?_
No, there is definitly nowhere the Path Copy entry. 
Perhaps only by me is the LNK-filetype on my Win7 wrong registered ?

Sorry, no french, I'm an old german :)

**Comment by clechasseur** [comment]
Ok, let's try something else.

Open regedit.exe and then open the HKEY_CLASSES_ROOT node. Navigate to the `.lnk` key and check the `(Default)` value. What does it say?

Then, navigate to the `lnkfile\shellex\ContextMenuHandlers` node. Is there a subkey named `PathCopyCopy`? If so what is the `(Default)` value of that key?

**Comment by TedBax** [comment]
With your help, I was able to solve my problem.

Create Add.PathCopyCopy.to.LNK.reg:

; -------
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\lnkfile\shellex\ContextMenuHandlers\PathCopyCopy]
@="{82CB99A2-2F18-4D5D-9476-54347E3B6720}"
; -------

After executing Add.PathCopyCopy.to.LNK.reg, the problem was solved.
It looks like the problem only affected me (?)

Many thanks for your help.

**Comment by TedBax** [comment]
With your help, I was able to solve my problem.

Create Add.PathCopyCopy.to.LNK.reg:

; -------
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\lnkfile\shellex\ContextMenuHandlers\PathCopyCopy]
@="{82CB99A2-2F18-4D5D-9476-54347E3B6720}"
; -------

After executing Add.PathCopyCopy.to.LNK.reg, the problem was solved.
It looks like the problem only affected me (?)

Many thanks for your help.

**Comment by clechasseur** [comment]
> After executing Add.PathCopyCopy.to.LNK.reg, the problem was solved.
> It looks like the problem only affected me (?)
> 
> Many thanks for your help.

Glad that I could help, although it's weird the key did not exist in the first place. The installer is supposed to create that.

Anyway since it's fixed I'll close this.
