### ISSUE TITLE
Not Working on Drives Other than C:\

### ISSUE THREAD

**Issue by jinmshu1** [clechasseur/pathcopycopy#124]
Long time user, but just upgraded to v18 from v12. Running the latest Windows 10 Pro v2004 without any issues.

I know this must be my fault, but I cannot get it copy Short Path on any other drive than C:\.  I've reinstalled as an Administrator, but still cannot get it to work on other drives. I'm using a Lenovo ThinkPad X1 Carbon 7th Gen with SSD with 6 partitions.

Any suggestions?

**Comment by clechasseur** [comment]
Short (8.3) filenames are not enabled by default on Windows 10 anymore - or they can be configured on a per-drive basis. This is outside of Path Copy Copy's control, unfortunately. For instance, see

https://superuser.com/questions/1505174/how-comes-that-short-filenames-8-3-are-created-in-one-partition-and-not-in-ano

You can enable the feature for all drives or enable it for each drive you want with `fsutil` it seems.

**Comment by jinmshu1** [comment]
Thank you very much!  This explains it to me and also gives me a possible solution.  Appreciate it!

**Comment by jinmshu1** [comment]
I successfully enabled Short (8.3) filenames on all of my partitions per the attached .jpg. I still cannot get PathCopyCopy to produce short paths for any other partition other than C:\.  I did re-install PathCopyCopy after enabling the Short (8.3) filenames

![Clipboard01](https://user-images.githubusercontent.com/68709945/89106245-356d6a00-d3f6-11ea-915f-3c5e5005693d.jpg)

Any other suggestions? I appreciate the help.  Thanks!

**Comment by clechasseur** [comment]
From the link above, it seems that simply enabling the setting for a drive won't generate the short names for existing files. You have to copy the files/directories and delete the original, or some other convoluted tricks:

https://superuser.com/questions/681330/how-to-force-short-name-8dot3-generation

Try it with a new file and see if it works.

**Comment by jinmshu1** [comment]
Thanks again. Yep, that handled it. Copying directories from, and back to, the affected partitions solved the problem. PathCopyCopy works fine.

Appreciate the help even though it had nothing directly to do with your work.  : )
