### ISSUE TITLE
[FEATURE] Allow custom commands to be shown only for files (or only folders)

### ISSUE THREAD

**Issue by ggbbrr** [clechasseur/pathcopycopy#125]
Some custom commands should appear only for files. e.g. "remove file extension"

Others should appear only for folders. e.g. "recursive"

It would be nice to be able to specify that a command should only be visible for files (or only folders).

**Comment by clechasseur** [comment]
This feature has been implemented and will be part of the next release.

**Comment by ggbbrr** [comment]
How does one specify 'only for file' or 'only for folder' ?

Just can't find the option. v20.0.

EDIT : sorry, found it. Display selection.
