### ISSUE TITLE
[BUG] second monitor not detected after update

### ISSUE THREAD

**Issue by finntiger** [clechasseur/pathcopycopy#126]
**Describe the bug**
After update from PathCopy version 18 to 19 and restart of the system, the second monitor was not detected anymore.
I tried with a different monitor (both connecting with HDMI) with no success.
A new restart did not help.
I removed PathCopy 19 and reinstalled version 18: second monitor was detected again after restart.

**To Reproduce**
see description above

**Expected behavior**
second (external monitor should be supported

**Screenshots**
no

**Software (please complete the following information):**
 - OS: Windows 10
 - Path Copy Copy Version 19.0

**Additional context**
Dell notebook computer

**Comment by clechasseur** [comment]
What do you mean by "not detected anymore"? Do you mean that Path Copy Copy cannot be displayed on that monitor, or that Windows simply cannot detect the monitor at all? That seems very unlikely to be related to Path Copy Copy...

**Comment by finntiger** [comment]
Hello,
the strange thing is that Windows did not detect the second monitor at all.

- I started Windows with two monitors working fine.
- I got the message that an update is available for Path Copy Copy.
- I downloaded and installed the update. Both monitors functioning.
- The update required a restart of Windows to take effect, which I did.
- Windows restated, but the second monitor was not detected. I tried with another monitor, same thing. I restarted Windows again, same thing.
- I removed Path Copy Copy 19 from the System. After Windows restart the second monitor was again detected and working fine.
- I installed Path Copy Copy 18 and everything is normal.

I’m aware that it seems unlikely, but this was my experience. There were no other changes to the system at the same time.

If you wish, I can try again installing version 19, just to see if the behavior can be reproduced.

BR,
Martti

**Comment by clechasseur** [comment]
> If you wish, I can try again installing version 19, just to see if the behavior can be reproduced.

I think it would be a good idea because it seems very unlikely to be because of Path Copy Copy. If it happens again the second time though I'll look into it.

**Comment by finntiger** [comment]
I just re-installed version 19 again. This time at work, not in the home office. The installation did not ask to restart Windows this time. The second monitor on HDMI was detected correctly (also after restart). Behaviour was also correct when using the docking station.
So far everything seems ok :-)
I'll try at home with my second screen there tonight and let you know.

**Comment by finntiger** [comment]
Sorry for the late answer. I tried at home and the second monitor was working fine. So, obviously no relation to Path Copy Copy 19.
However, after some other changes on the computer were made today, the second monitor is not detected anymore. There must be a flaw in my system that provokes it. But thats not your concern.
Take care!
