### ISSUE TITLE
[BUG] Long UNC Path (follow symlink) contains stray string

### ISSUE THREAD

**Issue by jackhab** [clechasseur/pathcopycopy#127]
**Describe the bug**
The symlink path resolution works fine but the path contains stray string which makes the path unusable.

Symlinks pointing to network location contain "?\UNC\".
Symlinks pointing to local drives contain "\\\\?\".

For example:
Symlink to network: \\\\?\UNC\dc2012\system\mail
Symlink to local drive: \\\\?\C:\Users\User\OneDrive

**To Reproduce**
Enable  Long UNC Path (follow symlink) in Settings.
Map a location via symbolic link in command line:
mklink /d LinkedPath c:\some\path
Explorer > right click LinkedPath > Path Copy > Examine the path

**Expected behavior**
\\\\dc2012\system\mail
C:\Users\User\OneDrive

**Software**
Path Copy Copy Version 19.0

**Comment by clechasseur** [comment]
This is actually a valid path. See
https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#example-ways-to-refer-to-the-same-file

**Comment by jackhab** [comment]
This is a valid path from Windows API point of view, but since this utility is used in Windows Explorer the ultimate validity test, IMHO, should be whether the path can pasted back to Explorer path drop-down or into File Open dialog box.

The only program which I've found to accept these paths is PowerShell.

**Comment by clechasseur** [comment]
It's strange that it doesn't work - you're right, they need to be usable through Explorer. I'll look into it.

**Comment by clechasseur** [comment]
This bug is fixed. The next release should no longer copy non-working paths.
