### ISSUE TITLE
[FEATURE] Path Copy Copy to SORT INTERNALLY when Multiple paths are copied - ID_20200817_004820

### ISSUE THREAD

**Issue by discovery747** [clechasseur/pathcopycopy#129]
**Is your feature request related to a problem? Please describe.**
= = = START
Path Copy Copy to SORT INTERNALLY when Multiple paths are copied - ID_20200817_004820
= = = END

**Describe the solution you'd like**
= = = START
What it currently does paste, - also, ever since I know Path Copy Copy since 2011 ...
D:\03
D:\01
D:\02

What I desire and is normal/better to paste ... (currently I priory sort in Excel to get the below ...!)
D:\01
D:\02
D:\03
= = = END

**Describe alternatives you've considered**
= = = START
Currently, I paste in Excel, Sort, and Paste Special as simple text - 
Failing to Paste Special (as it some times happens), Excel would paste as table/cells eg in FrontPage, Word, etc like Rich Text Format editors ...! 
Using Excel as in intermediary step is unnecessary 1. Software 2. Steps 3. error-prone etc ...!
Note - Current Version of Path Copy Copy 19

![xxAdrian_20200817_004031 W10 File Manager Screenshot](https://user-images.githubusercontent.com/33941787/90344614-f52bff80-e023-11ea-82f8-cf3da94b2d7c.jpg)

![xxAdrian_20200817_003821 WinVer at SORT INTERNALLY when Multiple paths are copied](https://user-images.githubusercontent.com/33941787/90344401-1855af80-e022-11ea-9400-fc21673856d8.jpg)
= = = END

**Additional context**
= = = START
Thank You Very Much for this GREAT Software ...!
(also,) a Bug Suggestion "After the recent Windows 10 Update no longer copies ".URL local PC files path"" was priory submitted ...!
= = = END

**Comment by clechasseur** [comment]
This has been implemented and will be available in the next version.
