### ISSUE TITLE
Virus Scan of EXE file detects Gen:Variant:Kazy - a generic detection for Vundo

### ISSUE THREAD

**Issue by URaVIP2me** [clechasseur/pathcopycopy#13]
BitDefender Total Security 2017 Build 21.023.1101

**Comment by URaVIP2me** [comment]
https://en.wikipedia.org/wiki/Vundo

**Comment by clechasseur** [comment]
I've had issues with false positives in the past, there's not much I can do about them. VirusTotal mentions two positive detections on the installer:

https://www.virustotal.com/fr/file/851475cd14e2b7ccef0bb778766affb00cc76512d77f06984aba4373a784c241/analysis/

...but apparently not with BitDefender. Might be different from version to version I guess.

Clearly seems like a false positive. Closing this.
