### ISSUE TITLE
[BUG] .ico files cause DataGridView errors in Settings GUI

### ISSUE THREAD

**Issue by moon6969** [clechasseur/pathcopycopy#132]
**Describe the bug**
.ico files when assigned to a PathCopyCopy sub-menu work as expected, but cause the following error in the Settings GUI:

> DataGridView Default Errror Dialog: System.FormatException: Formatted value of the cell has a wrong type.
![PCC-ico-err-01](https://user-images.githubusercontent.com/30491315/91768155-20425180-ebd5-11ea-8635-028da74eb76e.png)

The error dialog pops up for each Separator line, and after all errors are OKed you can see a red X (image not found) icon next to each Separator:
![PCC-ico-err-02](https://user-images.githubusercontent.com/30491315/91768608-c42bfd00-ebd5-11ea-9020-30a4a97c97d9.png)

If you force the DataGridView to refresh (eg: scroll the settings window), all the errors pop up again.
If you select a Seperator line, it starts an endless loop of the errors (requiring the termination of PathCopyCopySettings.exe)

I tested a few different .ico files varying resolutions and all failed...
[PathCopyCopy-icon-issue.zip](https://github.com/clechasseur/pathcopycopy/files/5152797/PathCopyCopy-icon-issue.zip)
Even https://raw.githubusercontent.com/clechasseur/pathcopycopy/default/icons/settings.ico errored!

**To Reproduce**
1. Open PathCopyCopy Settings (Right-click on a file in Explorer → PathCopy → Settings)
2. Assign .ico to "Copy Short Name" (ensure "Submenu" is checked)
3. Click Apply to save
4. Force the DataGridView to refresh (resize the Settings window)
5. Boom (, boom, boom,,,,)

**Expected behavior**
No error dialogs!

**Software**
 - OS: Microsoft Windows [Version 10.0.18362.1016]
 - Path Copy Copy Version 19.0

**Comment by moon6969** [comment]
I deleted HKEY_CURRENT_USER\Software\clechasseur\ so there were no assigned icons.

I noticed that if I assign a .ico to an entry that appears _after_ the first Seperator (eg: 'Copy Short Path' & below), thereafter I can add .ico's without error to any entry.

**Comment by clechasseur** [comment]
This has been fixed and the fix should be available in the next release.
