### ISSUE TITLE
[FEATURE] An ability for changing items position

### ISSUE THREAD

**Issue by amymor** [clechasseur/pathcopycopy#136]
Hello

Here is default items position:
https://imgur.com/EeKYpyk

And here is what I want it to be:
https://imgur.com/RXXQ4Hu

Any way?

TY

**Comment by clechasseur** [comment]
Unfortunately, this is impossible. The position of Path Copy Copy's items in the contextual menu is determined by the shell and we have no control over it. Sorry.
