### ISSUE TITLE
[FEATURE] Chinese language support

### ISSUE THREAD

**Issue by clechasseur** [clechasseur/pathcopycopy#138]
@littlegolden provided a PR to integrate Chinese language support.

**Comment by clechasseur** [comment]
It looks like the @littlegolden account has been closed and the PR is now gone... so I guess we'll drop this.

**Comment by blackcrack** [comment]
hmmm.. 
嗯，Reactos 应该可用，应该尽快完成，即使你在没有人的情况下建立一个中国分支来阻止 Reactos 可用，因为这将使世界上每个人受益

向中国致以许多问候

锄
这
行星

HTP :) \*thumpsup*
