### ISSUE TITLE
Getting machine name rather than drive name for internet path

### ISSUE THREAD

**Issue by n8craig** [clechasseur/pathcopycopy#139]
I expect to get an internet path that begins with the drive name like

`file:///C:/Program%20Files/Path%...`
This is what the settings indicates I should be getting. What I get instead is something formatted as the following, which is missing a "/" and starts with the machine name rather than the drive name.

`file://machine_name/Users/User/Documents/...`

_Do I not have some setting correct?_ I looked in the wiki and other documentation. If there's something I missed it. Thanks in advance and sorry if I missed something obvious. This looks like a handy tool.

Running Win 10 pathcopycopy 19

**Comment by clechasseur** [comment]
This is because you copied the path to a file that is in a valid network share. In such cases Path Copy Copy uses the file://machine_name/share/path/to/file format. If there is no valid share, it uses the file:///Drive:/path/to/file format.

(Sorry for the lag in the response 😄 )
