### ISSUE TITLE
[Question] Development builds and tests 

### ISSUE THREAD

**Issue by vnl** [clechasseur/pathcopycopy#14]
Hello Charles, 
I followed: https://pathcopycopy.codeplex.com/wikipage?title=Developer&referringTitle=Documentation
To an extent it is very well explained.  I wanted to help out with few of the issues here. To be honest I use Qt and so it kind of helps. So this would be the first C++ project outside using the library. 

My question is, I wanted to find out how to debug the application. Sorry about the novice question. 

I know this is not a typical GUI application and this is why I wanted some help if you have the time. Also, I do a lot of work with C# so C++ is a little harder lol.

**Comment by clechasseur** [comment]
The Settings application is the easiest to debug of course, simply launching it from the debugger will do. I suggest adding `/frompcc` to the command-line arguments, to avoid launching a revise attempt every debugging session.

To debug the contextual menu extension (PathCopyCopy project), you'll either need to hook to explorer.exe once the DLL is loaded or use an alternate explorer program. As a helper, I included one named mtExplorer in the `testing` directory. Set it as the program to launch in the debugger, then set breakpoints and hope for the best. Note that mtExplorer is a 32-bit application, so you'll need to compile PathCopyCopy in Debug/Win32 configuration.

Hope this helps. If you have more questions, don't hesitate to ask.
