### ISSUE TITLE
[BUG] Unattended install requires user input

### ISSUE THREAD

**Issue by wolfmar** [clechasseur/pathcopycopy#140]
**Describe the bug**
While tryping to do an unattended installation the installer asks if I want to setup just for the current user or for all users.

**To Reproduce**
1. Acquire a fresh windows installation
2. Run `PathCopyCopy19.0.exe /VERYSILENT /NORESTART /CLOSEAPPLICATIONS /RESTARTAPPLICATIONS`

**Expected behavior**
Unattended installation works without any user interaction.

**Software (please complete the following information):**
 - OS: Windows 10 1809 LTSC
 - Path Copy Copy Version 19.0

**Comment by clechasseur** [comment]
This must also be specified in the command-line parameters. See:

https://jrsoftware.org/ishelp/index.php?topic=setupcmdline

TL;DR pass either /ALLUSERS or /CURRENTUSER

Note that you can also pass /SUPPRESSMSGBOXES to avoid seeing any message box - but then you'll get an all-users install by default unless you also specify /CURRENTUSER.

**Comment by wolfmar** [comment]
Thanks for clearing that up!
I was looking at #44 and #58 for information, but somehow missed that link. May I suggest linking to it on the installation page in the wiki?

**Comment by clechasseur** [comment]
Yes, that was the plan but I've been putting it off for a bit too long I think. 😛
