### ISSUE TITLE
опа-на

### ISSUE THREAD

**Issue by wvxwxvw** [clechasseur/pathcopycopy#147]
Why is uploading new files prohibited, you don't need translations?

**Comment by wvxwxvw** [comment]
If necessary, take it from me. I will not delete for a short time.
https://github.com/wvxwxvw/pathcopycopy/tree/default/PathCopyCopy/localization/PathCopyCopyLocalization_ru

**Comment by clechasseur** [comment]
> Why is uploading new files prohibited, you don't need translations?

I'd love translations, but you can't commit to the main repo without permissions, no. If you have a new translation, which is cool, please create a pull request so that I can take a look at it and merge it as needed. Thanks!

**Comment by wvxwxvw** [comment]
@clechasseur 
I don't know how to create a request, especially for a folder. If you want, then just take it yourself to link.

**Comment by clechasseur** [comment]
You've provided translations for one aspect of the program - the shell extension. But there's also the Settings application and the installer to translate. Did you plan to work on those?

**Comment by wvxwxvw** [comment]
Ну конечно, Я хотел полностью перевести. Я в общем то и раньше делал для себя ресурсный перевод. Вы можете как то это более дружелюбно для переводчиков сделать? Напромер одним фалом, например .mo или напрямую .po. Ну или может просто комплект файлов для перевода дадите?

[Google > Russian to English]
Of course, I wanted to fully translate. In general, I have done resource translation for myself before. Can you do this in a more translator-friendly way? For example in one file, like .mo or directly .po. Well, or can you just give a set of files for translation?

[Yandex > Russian to English]
Of course, I wanted to translate it completely. In general, I have done resource translation for myself before. Can you somehow make it more friendly for translators? Completely with one halyard, for example. mo or directly .po. Well, or maybe you can just give a set of files for translation?

[DeepL > Russian to English]
Of course, I wanted a full translation. I've actually done a resource translation for myself before. Is there any way you can make it more translator-friendly? For example, with a single file, such as a .mo or directly with a .po. Or maybe you could just give me a set of files to translate?
