### ISSUE TITLE
[FEATURE] Element to also rename the file.

### ISSUE THREAD

**Issue by ggbbrr** [clechasseur/pathcopycopy#149]
**Is your feature request related to a problem? Please describe.**

Right now PathCopyCopy has elements to Find-Replace and Find-Replace with regex.

Please add an option in those two elements (and maybe others) to also rename the file with the result of the Find-Replace in addition to copying the new name to clipboard.

Currently the Find-Replace element has 
- Find what, and
- Replace with.
Below those you could add a checkbox "Rename file ?".

It shouldn't be too hard to implement, since most of the code already exists.

Thanks for v20.0

**Comment by clechasseur** [comment]
This seems to fall a bit outside of the purpose of a path copy tool. Granted, my tool supports regular expressions, but to modify the copied path, not to rename files... I'll think about it.

**Comment by ggbbrr** [comment]
OK. NP.

I developed a program to do that but it's in AutoIt. It would be nice to have one program do both copy path and rename stuff :-)

See attached pic for some of the things my program (EZRename) does.

![ezr](https://user-images.githubusercontent.com/63499243/131611806-3068421c-1245-4b19-b4c2-f90c22c62117.jpg)

**Comment by ggbbrr** [comment]
Requesting githubers with the necessary Windows programming experience and knowledge to develop a context menu extension like PathCopyCopy to _rename_ files.

Permitting two levels of sub-menus would be great.

If I had the skills I would do it myself.

**Comment by clechasseur** [comment]
I just realized that it's possible to do this already by using the "Launch a command-line" option, albeit a bit convoluted.

Here's an example of a command that does this:

[rename_command.zip](https://github.com/clechasseur/pathcopycopy/files/7874016/rename_command.zip)

Feel free to import it and change the find/replace operation used within to something else.

**Comment by ggbbrr** [comment]
Hi, thanks. Ya it works.


Have a look at "Shell" mentioned in this thread : Shell - App Scripts

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Shell - App Scripts

Shell - posted in App Scripts: File Name: ShellFile Submitter: MahmoudFile Submitted: 24 Jul 2021File Updated: 0...
 |

 |

 |





****** Please :***   -  Do not give this email address to anyone.***   -  Do not put me on any mailing list.***  Thanks.*** 

    On Saturday, 15 January, 2022, 06:58:38 am IST, Charles Lechasseur ***@***.***> wrote:  
 
 


I just realized that it's possible to do this already by using the "Launch a command-line" option, albeit a bit convoluted.

Here's an example of a command that does this:

rename_command.zip

Feel free to import it and change the find/replace operation used within to something else.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
