### ISSUE TITLE
[FEATURE] path to shortcut file

### ISSUE THREAD

**Issue by eastaress** [clechasseur/pathcopycopy#150]
Thank you so much for making this program. I am using this program very usefully.

---

-The path I wanted.
C:\Users\username\Desktop\logfile.lnk

-the path i actually get
C:\setup.log

I wanted to create a shortcut file and get the path to that shortcut file. But what I got was the path to the file the shortcut pointed to.

Is there any way I can get what I want? If not, I would be really happy with this feature added.

**Comment by clechasseur** [comment]
Yes, there is. The option is named "Copy paths of shortcut (.lnk) files themselves" in the Options tab of the Settings.

![PathCopyCopySettings_bvFfBjy3Xn](https://user-images.githubusercontent.com/1435551/134788095-8cc7caed-6090-4f82-8423-fad941a1a777.png)

**Comment by eastaress** [comment]
Thank you very much. I will use it well.
