### ISSUE TITLE
How to copy short parrent folder path and long name ?

### ISSUE THREAD

**Issue by Baltazar500** [clechasseur/pathcopycopy#151]
Hi.

How to copy short parrent folder path and long name ? I did not find such a template, and I could not combine the short parrent folder path and long name :(

**Comment by clechasseur** [comment]
There is no default way of getting this. It's possible to build a custom command to get it, but it's non-trivial. Here's one that should work:

[ShortPathButLongName.zip](https://github.com/clechasseur/pathcopycopy/files/7272447/ShortPathButLongName.zip)

Unzip the file and then import the resulting .eccv3 file using Path Copy Copy's Settings application and you're good to go.

**Comment by Baltazar500** [comment]
>There is no default way of getting this. It's possible to build a custom command to get it, but it's non-trivial. Here's one that should work:

Yes, this is a crazy solution to this problem.

>Unzip the file and then import the resulting .eccv3 file using Path Copy Copy's Settings application and you're good to go.

Thanks, it worked
