### ISSUE TITLE
Search by the name of a file or folder in the Everything 1.5 Alpha program

### ISSUE THREAD

**Issue by oleg-sgh** [clechasseur/pathcopycopy#152]
Hello.
I can't send the name of a file or folder to the Everything 1.5 Alpha program.
Can this be done?
Windows 7x64.
[https://www.voidtools.com/forum/viewtopic.php?f=12&t=9787](url)

**Comment by clechasseur** [comment]
What do you mean exactly by "send to the Everything 1.5 Alpha program"? You can copy the name of a file/folder to the clipboard with Path Copy Copy and paste it into the program, I guess.

**Comment by oleg-sgh** [comment]
"You can copy the name of a file/folder to the clipboard with Path Copy Copy and paste it into the program, I guess."
This should be done by the program itself from the context menu.
Another option is to copy the name to the clipboard and run VBScript or Bat, which will run Everything and paste the name from the clipboard into it.
I tried this combination, but the file name disappears from the buffer.

**Comment by clechasseur** [comment]
Perhaps what you're looking for is the option to launch an executable with the filename, available to custom commands:

![PathCopyCopySettings_nVW709OHV9](https://user-images.githubusercontent.com/1435551/136120720-f0a3fee8-e941-4833-831d-48e78b9da31e.png)

If Everything 1.5 supports it, you could launch its executable and have the file name passed to it.

**Comment by oleg-sgh** [comment]
I did that.
Example:
Instead of the name "Thunderbird Setup 60.9.12"
The search bar will contain:
"C: \ Windows \ System32 \ Thunderbird" | "C: \ Windows \ System32 \ Setup \" | "C: \ Windows \ System32 \ 60.9.1"

**Comment by clechasseur** [comment]
It sounds like your path is missing quotation marks. Try asking Path Copy Copy to add them (it's also an option available to custom commands) and see if it fixes the issue.

**Comment by oleg-sgh** [comment]
The path to any name from anywhere in the search is appended: C: \ Windows \ System32 \
"C:\Windows\System32\Thunderbird Setup 60.9.1.exe"

**Comment by clechasseur** [comment]
> The path to any name from anywhere in the search is appended: C: \ Windows \ System32 "C:\Windows\System32\Thunderbird Setup 60.9.1.exe"

I don't know why that is. That's a question for the maker of the Everything program...
