### ISSUE TITLE
[BUG] Commands get inactive (greyed out)

### ISSUE THREAD

**Issue by A-Kazak** [clechasseur/pathcopycopy#154]
**Describe the bug**
![image](https://user-images.githubusercontent.com/97515759/161550251-9e5d0959-77fd-4eb1-83e6-5a2e7a602833.png)

**To Reproduce**
Steps to reproduce the behavior: no special steps. This happened right after installation.

**Software (please complete the following information):**
 - OS: Windows 10
 - Path Copy Copy 20.0

**Comment by clechasseur** [comment]
This is normal. UNC-related commands are greyed out unless you use them on an actual network share or shared folder.
