### ISSUE TITLE
Copy WSL Short Path (without filename)

### ISSUE THREAD

**Issue by harrysmith0** [clechasseur/pathcopycopy#159]
Maybe it is possible to create a Custom Command to Copy WSL Path but without the filename but I cannot work it out.

Great software,

Thanks

**Comment by clechasseur** [comment]
I've managed to create one but I admit it's counterintuitive. Maybe I could add an option to remove filename in the default options...

Anyway here it is:

[CopyWSLParentPath.zip](https://github.com/clechasseur/pathcopycopy/files/9966487/CopyWSLParentPath.zip)
