### ISSUE TITLE
Get path without filename

### ISSUE THREAD

**Issue by kofifus** [clechasseur/pathcopycopy#16]
is there a way to get the path without the filename ?

**Comment by clechasseur** [comment]
Yes, use the "Copy Long Parent Folder Path" command.

**Comment by kofifus** [comment]
ok great

It would be really great to have the ability to change the display strings

For example to me this is much more common sense:
Filename
Path  (what is now parent folder path)
Full Name (what is now path)

Thx

PS - thx for great SW :)

**Comment by clechasseur** [comment]
It's kind of possible. Create new custom commands based on each of the regular commands and give them different names. Apply no other changes to the paths in the custom commands.

**Comment by kofifus** [comment]
got it thx!
