### ISSUE TITLE
[FEATURE] Advanced options to create links with title

### ISSUE THREAD

**Issue by nmatt** [clechasseur/pathcopycopy#160]
Using a single custom command, I'd like to create links for systems like Jira or Confluence, where the link combines a URL and a title, both based on the original path. For example, the URL would be the transformed path, while the title would be the original path.

Example: For the path

    C:/Program Files/Path Copy Copy/PathCopyCopySettings.exe

the result of the custom command would be:

    [C:/Program Files/Path Copy Copy/PathCopyCopySettings.exe|file:///C:/Program%20Files/Path%20Copy%20Copy/PathCopyCopySettings.exe]

In other words, `[<original path>|<transformed path>]`.

A variation of this would have the title also being a transformed path, but differently transformed from the URL.

In general, what this feature requires is the ability to perform separate transformations of the same original path and then combine those separate transformations into a single string, Unless I'm missing something, this is presently not possible even in Expert Mode.

The current workaround is to use multiple (custom) commands and manually combine their results in a text editor.

**Comment by clechasseur** [comment]
It's presently possible to do this with some clever use of the stack elements, although I admit this feature is very technical and non-intuitive. Here's an example:

[WikiLink.zip](https://github.com/clechasseur/pathcopycopy/files/9967857/WikiLink.zip)
