### ISSUE TITLE
[QUESTION] Serial of external HDD?

### ISSUE THREAD

**Issue by dffvb** [clechasseur/pathcopycopy#166]
Hi there, I got here, because I want to address external HDD with robocopy not via the drive letter, but the serial number or any other unique identifier...  I read Pathcopy could do so. Not too sure, if this info was wrong or me doing it wrong?

**Comment by clechasseur** [comment]
Unfortunately no, there is no such feature in Path Copy Copy at the moment. One way I could think of doing this would be to craft a custom command with a series of hardcoded find/replace elements, each replacing a letter of one of your drives with its unique identifier. If you have a fixed set of drives and know their identifiers in advance, that could work.

**Comment by dffvb** [comment]
Thank you
