### ISSUE TITLE
[BUG] PathCopyCopySettings.exe reported as trojan/malicious by VirusTotal

### ISSUE THREAD

**Issue by greg-vv-are** [clechasseur/pathcopycopy#167]
**Describe the bug**
EXE "PathCopyCopySettings.exe" shipped with version 20.0 is reported as trojan/malicious by VirusTotal.
See: https://www.virustotal.com/gui/file/125a961bfce7ee4232765631d94e7c2d343cc9be71b0bdaaeac60f99d3d26d36/detection

**To Reproduce**
1. Go to https://www.virustotal.com/gui/home/upload
2. Submit file 'PathCopyCopySettings.exe'
3. See security scan result: 2 security vendors and no sandboxes flagged this file as malicious
   - MaxSecure reports : Trojan.Malware.300983.susgen
   - SecureAge reports : Malicious

**Expected behavior**
A VirusTotal security scan resulting in "No security vendors flagged this URL as malicious".
...so that the cyber department of my company let me continue to install and use PathCopyCopy on my professional laptop.

**Screenshots**
N/A

**Software (please complete the following information):**
 - OS: Windows 10
 - Path Copy Copy Version: 20.0

**Additional context**
N/A

**Comment by clechasseur** [comment]
Version 20.0 has been out for a while, and the hash on VirusTotal corresponds with the one I have here, so it's hasn't been tampered with. It's a false positive - it has [happened before](https://github.com/clechasseur/pathcopycopy/issues?q=is%3Aissue+is%3Aclosed+virus).

There's not much I can do about it. It will probably be unflagged at one point when they fix their antivirus, I guess. You can log onto VirusTotal and vouch for it.
