### ISSUE TITLE
[BUG] unable to remove stock entries from commands list

### ISSUE THREAD

**Issue by ulu** [clechasseur/pathcopycopy#171]
**Describe the bug**
I cannot remove stock entries from Commands list.

**To Reproduce**
1. Go to "settings" > Tab "Commands"
2. check a line
3. "Remove" button is inactive

**Expected behavior**
I want to be able to remove all entries and have a button for reset the settings.

**Screenshots**
<img width="374" alt="unable_to_delete" src="https://github.com/clechasseur/pathcopycopy/assets/809609/7f649329-5cae-4ed2-b9db-ef14d055229c">

**Software (please complete the following information):**
 - OS: Windows 10 Enterprise 22H2
 - Path Copy Copy Version 20.0

**Comment by clechasseur** [comment]
I think this might be confusing, because the Settings are supposed to display all possible commands. Why would you want to remove them from the list? You can just uncheck them.

**Comment by ulu** [comment]
I don't like to have unnecessary stuff in my context menu. So I like to get rid of the main menu and all sub menus of pathcopycopy. I only want the "full UNC path copy" option.

Best option for me would be to remove the main menu from context menu and make it available in windows start menu.

**Comment by clechasseur** [comment]
> I don't like to have unnecessary stuff in my context menu. So I like to get rid of the main menu and all sub menus of pathcopycopy. I only want the "full UNC path copy" option.

That's the purpose of the checkboxes next to each command in the Settings. You can deselect any command you don't want to display in either the main menu or the submenu. Any command you deselect won't show up in the contextual menu (barring bug #170 unfortunately).

Also note that you can disable the submenu altogether by deselecting the "Always show submenu" option (see below). When you do this, the submenu will only be displayed if you hold down the Shift key when opening the contextual menu.

![image](https://github.com/clechasseur/pathcopycopy/assets/1435551/734a4bea-a07c-4d7d-bf8e-aa5508440caa)

> Best option for me would be to remove the main menu from context menu and make it available in windows start menu.

If you added something to the Windows Start menu, how would you be able to apply it to a specific file or folder?

**Comment by clechasseur** [comment]
Since it's possible to accomplish what you describe in the current version, I'll close this.
