### ISSUE TITLE
Copy File/Folder Path context menu item glyph

### ISSUE THREAD

**Issue by JaredEStoddard** [clechasseur/pathcopycopy#172]
Using v.20.  I use the **Copy File/Folder Path** context menu item frequently -- but it does not have a glyph like **Path Copy** does.  Possible to create a glyph that is easy to ID (perhaps a "C:\\" in lime or yellow on black)?  The problem is that the menu item location can change depending on context, so a user must scan for it (textually) each time.  On _my_ last use, it was item 15/26.  

![PCC-CM](https://github.com/clechasseur/pathcopycopy/assets/15371483/7c841007-0c32-4f3f-af22-f84e86acb383)

**Comment by clechasseur** [comment]
Sorry for the late reply, but this is already possible. In the Settings application, you can assign an icon to any command, including the default ones. You can also Shift-click in the Icon column to have a command use the default icon if you'd prefer not to provide one.

![image](https://github.com/clechasseur/pathcopycopy/assets/1435551/f1505274-01f9-4b61-a86e-995012555d50)
