### ISSUE TITLE
[BUG] "& in the name"-issue

### ISSUE THREAD

**Issue by ZPMU** [clechasseur/pathcopycopy#175]
**Describe the bug**
A "&" in the name of a (custom) command will be swallowed when the context menu appears.
A "&&" in the name will be reduced to "&".

**To Reproduce**

0. Path Copy Copy 19.0 is installed
1. Open context menu, enter the "Path Copy" sub menu, choose "Settings…"
2. Create a "new" command based on arbitrary base command; enter for "Name": "A & B"; OK (2 times).
3. Open context menu: The newly created entry reads "A  B".
4. Enter again the Settings window, now "Edit" the newly created custom command and change the name to "A && B". Nod through.
5. Open context menu: The newly created entry reads "A & B".

**Expected behavior**
For whatever reason this "&"-swallowing happens (suppose it has to do with context menu handling API), it should be hidden from the user. Neither one should be faced with the fact that one has to repeat the "&" in order to let it appear at all; nor one should have to deal with the double "&" of custom command entries when handling them in PCC's windows.

**Software (please complete the following information):**
 - OS: Windows 10
 - Path Copy Copy Version 19.0

**Comment by clechasseur** [comment]
This has been fixed in v20.0, although strangely it wasn't documented in the `HISTORY` file:

https://github.com/clechasseur/pathcopycopy/blob/v20.0/PathCopyCopy/src/PathCopyCopyContextMenuExt.cpp#L818-L820

**Comment by ZPMU** [comment]
Thanks anyway!
