### ISSUE TITLE
[BUG] Loop detected

### ISSUE THREAD

**Issue by I3ordo** [clechasseur/pathcopycopy#176]
i got a loop detected error which has disabled any clipboard actions

is there a way to crash and restart path copy copy? i got a loop detected error which has disabled any clipboard actions.

don't want to restart the pc.

Created a custom action which was supposed to add double quotes to file basenames, then i switched from newlines per path to , multiple paths on the sameline , then the loop error occurred and reverting the option does not make path copy copy useable so either i restart the pc or restart the shell/path copy copy service?

**Comment by clechasseur** [comment]
This sounds like a bug, but I'm not entirely sure _what_ you mean by "loop detected". That doesn't sound like an error coming from Path Copy Copy. Could you perhaps share a screenshot of the error message?

There is no Path Copy Copy "service" per se. The main component is embedded in Windows Explorer, so you could kill and restart _explorer.exe_ if you wanted. The Settings application can also be safely killed and restarted if that is the issue.

**Comment by clechasseur** [comment]
Closing this for lack of user input.
