### ISSUE TITLE
[BUG] Why is this executable trying to contact Fastly CDN tcp://185.199.109.133

### ISSUE THREAD

**Issue by tristansly** [clechasseur/pathcopycopy#177]
**Describe the bug**
Why is this executable trying to contact Fastly CDN tcp://185.199.109.133

**To Reproduce**
Install firewall for notification

**Expected behavior**
Does App need network access? why?

**Screenshots**
Nah

**Software (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Path Copy Copy Version [e.g. 17.1]

**Additional context**

**Comment by clechasseur** [comment]
Apparently, this is a GitHub IP address: https://ipinfo.io/185.199.109.133

This is most likely the automatic update check that verifies if there's a new version. It downloads an [update file](https://github.com/clechasseur/pcc-updates/blob/master/UpdateInfo2.xml) to check what is the latest version and that file is hosted on GitHub.

If you want, you can disable the automatic update check and it should stop trying to download the file.
