### ISSUE TITLE
there is no ability to install Net Framework 3.5 on last Windows 10

### ISSUE THREAD

**Issue by shredder2003** [clechasseur/pathcopycopy#18]
It seems like Microsoft closed Net Framework 3.5 installation for Windows 10.

**Comment by clechasseur** [comment]
Weird, I have Windows 10 and I have .NET Framework 3.5 installed. It seems to be documented as such here:

https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10

Have you tried looking in "Windows Features"?

**Comment by shredder2003** [comment]
not bug, my bad.
Windows Update was configured to local server by domain politics, after deletion all Windows Update settings form registry, it download and install Net 3.5 OK.
