### ISSUE TITLE
[FEATURE] Add an icon in the context menu

### ISSUE THREAD

**Issue by JustALooker666** [clechasseur/pathcopycopy#185]
First of all, thanks for Path Copy Copy! 
Would it be possible to add an icon in the context menu so that **Path Copy Copy** stands out among other, mostly useless Windows menu items?

**Comment by clechasseur** [comment]
That's actually already the case. The contextual submenu item has a Path Copy Copy icon. Furthermore, in the Settings app, you can assign an icon to any command via the `Icon` column. If you want to use the default Path Copy Copy icon, you can Shift-click in the `Icon` column next to the command.

<img src="https://github.com/user-attachments/assets/3def3d47-82e3-49e9-859f-15b39916ab27" width="75%" alt="The Path Copy Copy Settings application, showing a tooltip for the Icon column"/>

**Comment by JustALooker666** [comment]
Amazing! I didn't even notice the icon column and I can add any icon I like.
Thanks a lot.
