### ISSUE TITLE
1.29 MBPathCopyCopy14.0.1.exe can't download

### ISSUE THREAD

**Issue by sojey** [clechasseur/pathcopycopy#19]
china use network proxy, can't download this url, but can work in other 2.

**Comment by clechasseur** [comment]
What do you mean by the "other two"? Unfortunately, I'm not sure I can be of much help if China's proxy blocks this GitHub URL... I guess I could set up a mirror on Bitbucket or some other place.

**Comment by clechasseur** [comment]
I have copied the 14.0.1 installer at this location:

https://bitbucket.org/clechasseur/pcc_backup/downloads/PathCopyCopy14.0.1.exe

Is that accessible to you?

**Comment by sojey** [comment]
other 2 url there is 3 download link ^_^

your provide the url adress can be download, but speed only 1~5 kb/s.

I purchased the network provide, it can access most of the network blocked by the Chinese firewall, but only a lot of download links in the github.com project are very slow, or will automatically disconnect, I do not know why.

**Comment by clechasseur** [comment]
As long as you can download it, it's fine I guess - even if it's slow, it'll get there eventually :-) I'll consider this resolved.
