### ISSUE TITLE
Get paths recursively

### ISSUE THREAD

**Issue by clechasseur** [clechasseur/pathcopycopy#2]
Add an option to get paths recursively somehow.

Original issue: https://pathcopycopy.codeplex.com/workitem/11368

**Comment by vnl** [comment]
Just adding the desc. I will give this a shot. 

Add a command that would copy the names of all files and folders inside a selected directory (possibly recursively). Suggested by Nati30:
very simply , like the output of command "dir /s" . 

I just want to click on one (or more) folders and copy to clip all folder names and file names inside of it to get the folder names of the ones that I selected - your current version gives me that. but not the subfolders.

**Comment by clechasseur** [comment]
Just a note: I'm not a big fan of adding a command for this (there are many commands already). I think this would be better as a pipeline option for custom commands. You could also add it as a global option if you like.

**Comment by vnl** [comment]
I agree on the custom commands if necessary. Also, my build is broken completely, not sure which SDK I am missing (must be the XP support) in VS2017. So this would take longer than usual.

**Comment by clechasseur** [comment]
This feature has been implemented and will be shipped in the next version.
