### ISSUE TITLE
Ignoring updates does not work

### ISSUE THREAD

**Issue by clechasseur** [clechasseur/pathcopycopy#20]
When the software update form appears, choosing "Ignore this update" will fail to save the ignored update and thus, the update will be offered again a week later.

**Comment by clechasseur** [comment]
This is the problem:

https://github.com/clechasseur/pathcopycopy/blob/master/PathCopyCopySettings/Core/UserSettings.cs#L482

I think that simply calling `ToString()` would work.

**Comment by sambuev** [comment]
Yes, very annoying, had to update it on Windows 10

**Comment by clechasseur** [comment]
Fixed in `master`, will be part of the next release.
