### ISSUE TITLE
DrWeb engine has identified Trojan.Vittalia.13604 infection in release 14.0.1

### ISSUE THREAD

**Issue by timirf** [clechasseur/pathcopycopy#21]
DrWeb engine has identified Trojan.Vittalia.13604 infection in release 14.0.1
![pathcopycopy1401_infected_by_trojan_2017-10-11_111138](https://user-images.githubusercontent.com/32700608/31429890-e949c84a-ae77-11e7-81d7-2284a5ae7e98.jpg)

**Comment by clechasseur** [comment]
Most likely a false positive, I get them pretty much every release. Looking at the comment from PayloadSecurity:

https://www.virustotal.com/#/file/9fe17f3b8d40a909ed16dc19a09adff5f0dd02fb1bb58c8739d03c266d15d406/community

...it looks like heuristics are based on codeplex URIs... weird.

Anyway, like always, there's not much I can do about it. Closing this.
