### ISSUE TITLE
F-Secure SAFE report PathCopyCopyRegexTester.exe as PotentiallyUnwanted in 14.0.0

### ISSUE THREAD

**Issue by da9l** [clechasseur/pathcopycopy#23]
https://www.f-secure.com/sw-desc/pua_w32_app_online.shtml

I see that this happens occasionally but I just want you to know it for the record.

**Comment by clechasseur** [comment]
I've seen false positives with antivirus products in the past. Perhaps that's the same? Not sure what it's flagging as "unwanted" in that case.
