### ISSUE TITLE
The .exe download is marked as unverified publisher..

### ISSUE THREAD

**Issue by PhilipOakley** [clechasseur/pathcopycopy#25]
Is it possible to get a code signing certificate for you / the code so that the downloads pass basic checks - this is for a work IE 11 with anti-virus checking, that says "The publisher of this program couldn't be verified [Learn more](https://support.microsoft.com/en-gb/help/17436/windows-internet-explorer-download-files-from-web)".

I believe there are 'free Open Source developer code signing certs' available. (favourite search engine should find a few providers).

The Git for Windows developer I think uses 'Certum Level III CA'

**Comment by clechasseur** [comment]
Interesting, I'll try to explore this.

**Comment by clechasseur** [comment]
Implemented. Next version (17.x) will be signed with a Certum open-source certificate.

**Comment by blackcrack** [comment]
@clechasseur ,  i hope we become not a "Pitzahat" W0rld domination in security,
hold in the brain: 

**"If M$ say it's not secure, can it be secure enough for the world .."**
and don't forget they are partners (with peoples in the hidden too .. ) ... :\

I hope, Reactos become fast enough usable and stable enough ..

best regards
Blacky
