### ISSUE TITLE
Cannot install, the .exe is quarantined by Symantec

### ISSUE THREAD

**Issue by marefundo** [clechasseur/pathcopycopy#26]
![grafik](https://user-images.githubusercontent.com/14966624/34617858-05b19f04-f23d-11e7-9077-065c391aec69.png)

**Comment by clechasseur** [comment]
Weird, I have the same antivirus and it's fine here. What version of the virus definitions do you have? Did you try to run LiveUpdate?

Perhaps it also has to do with the Download Insight sensitivity level. Mine is configured at 1 (the lowest value), what about you?

**Comment by marefundo** [comment]
The virus definitions are up to date, I also run LiveUpdate, but still the .exe goes to the quarantine.
The Download Insight security level is at 5, however I cannot change (blocked by admin).

**Comment by marefundo** [comment]
By mistake hit the close button.

**Comment by clechasseur** [comment]
Unfortunately, there's little I can do in cases like this, it's a bit like false positive detections by some antivirus... You can report the false positive here it seems: https://submit.symantec.com/false_positive/

Other than that, your only option is to talk to your admin so he can whitelist the Path Copy Copy installer. You may also want to try an older version in case it works (not an ideal solution, but hey).
