### ISSUE TITLE
Request from a user: Write filepaths into a textfile

### ISSUE THREAD

**Issue by TedBax** [clechasseur/pathcopycopy#27]
(sorry, very bad english)

Wonderfull software, thank you very much !

Now:
Custom Command / Options:
   Launch executable with path(s) instead of copying to the clipboard
   Executable:  C:\test.exe

Request:
Custom Command / Options:
   Launch executable with **filelist.txt** instead of copying to the clipboard
   **filelist.txt**:  C:\myfiles.txt
   Executable:  C:\test.exe

**Comment by clechasseur** [comment]
This has been implemented in the next version (17.0).
