### ISSUE TITLE
User Request: short unix path

### ISSUE THREAD

**Issue by gmonkman** [clechasseur/pathcopycopy#29]
Use the product all the time as a windows user writing a lot of python. Really like it.

I frequently use unix path and short path, short path is useful when creating command line arguments to execute a .py, but I have to change the \ to / by hand.

Would be good if the unix option had a short unix path, so I could just copy it straight into batch scripts which execute multiple .py's or straight into the command line.

**Comment by clechasseur** [comment]
Because short paths are deprecated, I'm reluctant to add this. It would be easy to create a custom command for this though: choose "Copy Short Path" as base command, then choose to replace all backslashes with forward slashes.

**Comment by gmonkman** [comment]
Thanks for your advice, i'm sure that will suffice.
