### ISSUE TITLE
get FQDN

### ISSUE THREAD

**Issue by Triptrop** [clechasseur/pathcopycopy#30]
I need the possibility to get a path of a file which contains the full qualified domain name (FQDN).
For example, with Windows power shell I can get it by:
[System.Net.Dns]::GetHostByName("computer01")

"computer01" would be the computer name of the file server where my file is located.

Explanation:
The issue with the current "UNC path" or "internet path" is the following:

Scenario 1:
File is on a server:
subdomain1.domain.com

My computer is in:
subdomain2.domain.com

When I use e.g. "UNC path" of the file I get:
\\server.subdomain1.domain.com\directory\filename
--> everything is fine, everyone can open the file from the UNC-link.

Scenario 2 (this is the issue now):
File is on a server:
subdomain1.domain.com

My computer is also in:
subdomain1.domain.com

A colleagues computer is in a different domain:
subdomain2.domain.com

When I use e.g. "UNC path" of the file I get:
\\server\directory\filename
because my computer and the server with the file are within the same domain and subdomain, so my computer "thinks" there is no necessity to output the subdomain of the server.

As a result, my colleague with his computer in subdomain2 is not able to open the file (within subdomain1) from the UNC-link I send him, because his computer (within subdomain2) "cannot find the path specified".

**Comment by thedoctrine101** [comment]
That is a good idea too. Would not be used frequently, but would definitely be handy to have if ever needed. I support this enhancement.

**Comment by Triptrop** [comment]
Our company currently moves from Win7 to Win10 and from continent-wide domains to worldwide domains which is basically causing the problem described above.
So, this issue affects thousands of people in our company, daily ;-)
... it's really a pain in t.....

**Comment by clechasseur** [comment]
This has been implemented in `master` and will be part of the next release, tentatively known as 16.0.

**Comment by Triptrop** [comment]
Great news.
Thanks a lot :-)))
