### ISSUE TITLE
Update windows loads everytime logon

### ISSUE THREAD

**Issue by NetmanAdz** [clechasseur/pathcopycopy#31]
Would like to turn this off via the Registry can you advise me which value will allow that?

Many thanks  Adz

**Comment by clechasseur** [comment]
I'm sorry, but can you clarify what you mean by "update windows"? Perhaps a screenshot would help.

**Comment by NetmanAdz** [comment]
Hi

Many thanks for getting back to me ☺

Sorry should have said ‘Update Window’ not ‘Windows’

Please find attached I would like to stop appearing every time I logon as I want to check for update manually (via the windows registry)

Is that possible?

Kind Regards and many thanks for a lovely product

Adam

**Comment by NetmanAdz** [comment]
Thank you for contacting the service desk on 20/02/2018 12:40.

Your ticket has been logged with ID 0068005. 

Our portal is available to you to track, and update, any ticket which you have opened with Dataspire.  This portal is accessible through this link: https://servicedesk.dataspire.co.uk.

Should you wish to provide any further information that would help us, please update our portal or reply to this mail.

Thank you.

Dataspire Solutions Ltd
Lowry Mill, Manchester, M27 6DB 
Office: 0845 603 1233

Follow us: 
Website: www.dataspire.co.uk

**Comment by clechasseur** [comment]
Sorry, it seems that the attachment did not make it to GitHub. Could you log in with the web site and upload it there?

**Comment by NetmanAdz** [comment]
![20180220_091111 small](https://user-images.githubusercontent.com/36533082/36472812-ce609f50-16ea-11e8-8f01-a82433509e8a.jpg)

**Comment by NetmanAdz** [comment]
Hi - maybe I didn't explain the correctly as what I have done is used:

"C:\Program Files\Path Copy Copy\PathCopyCopySettings.exe", which is part of the main install, to set the setting I want (in this instance the 'Check for Updates Automatically)  then I can export the setting using the 'Export Settings' button and use this .reg file via logon script to be applied to all users.

Many thanks for you help.  I don't think this is a bug :-)
