### ISSUE TITLE
Path is copied on right click, even if <Ctrl> is not pressed

### ISSUE THREAD

**Issue by Merlin2001** [clechasseur/pathcopycopy#32]
### Summary
When the setting "*When user holds down Ctrl key when opening contextual menu, use this command:*" is enabled, the chosen command is performed on every right click, **regardless of the Ctrl key state**. This can lead to **data loss** due to overwriting the current clipboard contents with the copied path.

### Steps to reproduce
1. Copy the text `Text that should remain in clipboard` to your clipboard.
2. In the PathCopyCopy settings, enable *When user holds down Ctrl key when opening contextual menu, use this command:* and set it to *Copy long UNC path*. Save the settings.
3. Right click on a file or folder without touching the Ctrl key.
4. Now paste from clipboard.

### Result
The pasted text is the UNC path to whatever file or folder you clicked on.

### Expected Result
The pasted text should be `Text that should remain in clipboard`

### Workaround
My current workaround is to use a clipboard manager (namely [Ditto](http://ditto-cp.sourceforge.net)) to keep my contents from being overwritten.

This happens to me in PathCopyCopy v15.0 - I'm not sure, if this is a regression, though, since I didn't use the feature in earlier versions.

Thanks for having a look! :)

**Comment by clechasseur** [comment]
I cannot seem to reproduce this - here, the text only gets copied to the clipboard if I do hold the Ctrl key.

Can you tell me which OS you are running and if it's a 32-bit or 64-bit version?

**Comment by Merlin2001** [comment]
Hi Charles,

of course: I'm on a **64-bit** Microsoft **Windows 7** Enterprise Service Pack 1 (Build 7601 and the following .NET Framework Versions are installed: CDF, v**2.0**.50727.5420 (SP2), v**3.0**.30729.5420 (SP2), v**3.5**.30729.5420 (SP1), v**4**, v**4.0**.

I also made a short screencast showing the behavior:
![pathcopycopy 32 - inconsistent behavior when ctrl action is defined](https://user-images.githubusercontent.com/13134791/41523989-30c435e2-72dc-11e8-9b85-2392c058b768.gif)

Note, though, that the behavior has been **all over the place** during preparation of the screencast. During the first take, variant _01_ (select, then right click w/o CTRL) also got copied to clipboard (with no CTRL pressed). There seems to be some **random element** to it... :smile:

**Comment by clechasseur** [comment]
After viewing your screencast, I tried the same test I had done before and this time I reproduced it... There does seem to be some kind of randomness to it...

**Comment by clechasseur** [comment]
This has been fixed in `master` and will be part of the next release.

**Comment by radsdau** [comment]
I can't confirm this exactly, but I suspect using Ctrl-Shift-N (new folder) in win explorer also triggered this bug. I have been fighting for it literally years, my clipboard frequently getting corrupted.
Seems all good now in V18. Thanks.
