### ISSUE TITLE
User request: Send path to new E-Mail

### ISSUE THREAD

**Issue by soendi** [clechasseur/pathcopycopy#34]
Hey there, thanks for doing this very helpful piece of software.
Is it possible to implement an option to send the path to a new email?
I managed this already - but it would be nicer, when it would be choseable directly as a standard option.

I just did a batch file, containing:
`start "" mailto://?body=%1`
and chose this batch file to launch as the executable file.

Unfortunately, it depends on the used mailto handler/software, whether the link will be working or not.

Chrome/inbox -> works properly
Lotus Notes -> replaces "%20" by "[space]" - file://-link won't work like this.

Had no other e-mail clients...

Think, this would be a piece of cake for you, isn't it?

Cheers
soendi

**Comment by clechasseur** [comment]
Not sure this is so easy. There could be mailer-specific issues.

It seems to me like your solution is good enough and if not, simply copy the path to the clipboard and paste it in a new e-mail.

I'll close this for now.
