### ISSUE TITLE
Add Feature - Copy Path (UNC or not) and/or Name WITH quotes on both ends

### ISSUE THREAD

**Issue by thedoctrine101** [clechasseur/pathcopycopy#37]
In Windows, sometimes the quotes are necessary when copying a file name, or path, or UNC path, especially in the command line. Would be nice to have those added as a context menu options, and they could be captioned like: "UNC Path with Quotes", and "Name with Quotes", and "Path with Quotes", etc.

Examples of results when pasting:

"\\servername\foldername\subfoldername"
"\\servername\foldername\subfoldername\filename.txt"
"filename.txt"
"C:\temp\filename.txt"
"c:\temp"

**Comment by blackcrack** [comment]
this should be normally 
\\Servername\ 
i have run an sambaserver, at the basementwhy i know this ..
just a bit help.. if you have the same account like in workgroup and user, can you browse
with \\servername\(pulldownlisting by windows automatically {normally})

best regards
Blacky

**Comment by clechasseur** [comment]
This is already possible to do by creating a custom command based on the existing command required. In the custom command's Options, select `Enclose in quotation marks`.
