### ISSUE TITLE
Suggestion: add FileHash function comparable to Get-FileHash from PowerShell

### ISSUE THREAD

**Issue by unquietwiki** [clechasseur/pathcopycopy#39]
-  https://github.com/okdshin/PicoSHA2 is an MIT-licensed C++ component, that may be useful to accomplish a SHA-256 file hash.
-  https://msdn.microsoft.com/en-us/library/system.security.cryptography(v=vs.110).aspx Microsoft has SHA-256 / 384 / 512 functions in its libraries.

This functionality is useful in projects such as maintaining content found on https://chocolatey.org/packages

**Comment by clechasseur** [comment]
I'll keep this as a possible enhancement, but this is a bit specific, I think. Still, interesting idea.

**Comment by unquietwiki** [comment]
@clechasseur There's some other tool out there that I found, that has similar functionality; but I believe required a paid license. It has also been standard practice for years to "compare the file hash" of downloaded content, if you're paranoid about security; so there is definitely a use case here. I'm strung between some C# and JS projects, else I'd pitch in myself on this.

**Comment by penCsharpener** [comment]
7zip installs a context menu entry that provides this if I'm not mistaken

**Comment by unquietwiki** [comment]
@penCsharpener (checks) Yeah, there is a CRC-SHA menu context option on systems that have 7-zip correctly installed. The context menu seems to be really hit or miss on when I load it onto systems. :/

**Comment by TekBear** [comment]
I use file menu in total commander software as it also has this feature. Given you can add custom commands are there any general command line tools that take checksum method (CRC32,MD5,SHA1/256/512) and file name as command line arguments. One method would be to write a script that uses certutil.exe (I think it is only found on win 7 or higher) or [powershell cmdlet]( https://www.nextofwindows.com/5-ways-to-generate-and-verify-md5-sha-checksum-of-any-file-in-windows-10) .  I have not fond any tools that run on older windows.

**Comment by blackcrack** [comment]
http://implbits.com/products/hashtab/
is a snapin as a dll file directly on the explorer, right Mouse, Property's and one of the tab ;)
Pathcopy it's the wrong place for it ;)

best regards
Blacky

**Comment by clechasseur** [comment]
I think there are other options out there… I myself use the 7-zip menu and it seems to work fine. I'll close this.
