### ISSUE TITLE
Run external app with path as argument

### ISSUE THREAD

**Issue by clechasseur** [clechasseur/pathcopycopy#4]
Add an option to run an external application with the path as argument, instead of sending it to the clipboard.

Original issue: https://pathcopycopy.codeplex.com/workitem/11394

**Comment by clechasseur** [comment]
This is now implemented and will be part of the next release, tentatively named 15.0.

**Comment by wamsea** [comment]
Hi @clechasseur 
Thanks for the feature.  Need you help.
I want to run a java class with file full path as argument or run a windows .bat with file as argument.

Could you please let me know as to how the usage would look like. How do I read the argument.

Thanks,
Vamsi.

**Comment by clechasseur** [comment]
Not sure I understand your question (and sorry for the late reply). The file path is passed as the first argument to the program being launched. Is that what you meant?

**Comment by clechasseur** [comment]
I'll close this again, you can perhaps ask on StackOverflow.
