### ISSUE TITLE
Suggestion: copy .lnk paths!

### ISSUE THREAD

**Issue by zeb0z** [clechasseur/pathcopycopy#41]
It would be nice to be able to copy the paths of .lnk (shortcut) files, not just the target of what the shortcut points to.  Thanks

**Comment by thedoctrine101** [comment]
Good idea. Some shortbut properties dialog box do not show the target field for some reason. This feature would circumvent that where applicable. I support this enhancement idea.

**Comment by clechasseur** [comment]
Just realized this is a duplicate of #7 . Closing this one.
