### ISSUE TITLE
Enhancement: Provide option to remove pathcopycopy submenu item from context menu and only show items configured for "main menu"

### ISSUE THREAD

**Issue by luvtoride** [clechasseur/pathcopycopy#42]
For users with a lot of context menu items this option would provide a way to unclutter the context menu just a little.

**Comment by clechasseur** [comment]
How about unchecking "Always show submenu"? Then the submenu no longer shows up unless you hold down the Shift key when right-clicking.

**Comment by clechasseur** [comment]
Closing this as this seems implemented already.
