### ISSUE TITLE
Convert UNC path to SMB path

### ISSUE THREAD

**Issue by DiscoGas** [clechasseur/pathcopycopy#46]
Hello!

Please could you add another option to convert a UNC path to SMB path?
Quite similar to Internet path, smb://path instead of file://path

Currently it would be really useful for PC to Mac sharing!

Thanks!
Regards

**Comment by clechasseur** [comment]
This has been implemented in `master` and will be part of the next release.

**Comment by DiscoGas** [comment]
Hello Charles,
Thanks for the release!
I tried the smb option and every time I clicked on a link, it tries to authenticate. Then asks to select the connection to the NETLOGON or SYSVOL folders instead of opening the correct address in the link.
Please could you review it.
Thanks!
Cheers

**Comment by DiscoGas** [comment]
Hello Charles,
I mean, please could you re-code smb option to display and copy the parent folder path similar to "Copy Long UNC Parent Folder Path".

After some testing, I realized that for Macs the issue is adding the file name at the end.
Right smb://server-name/folder/../folder/
Wrong smb://server-name/folder/../folder/file-name.xxx

Thank you!

**Comment by clechasseur** [comment]
The Samba command seems like too fringe a feature to add a new command to copy the parent folder path... and if I change the default behavior, it will seem out-of-place compared to the Internet command.

I suggest you create a custom command based on Copy Samba Path and use regular expressions to keep only the folder path:

**Find what:** `^(.*/)[^/]*$`
**Replace with:** `$1`

In my tests here it succeeds in copying the parent folder path, including terminating `/`.
