### ISSUE TITLE
Support WSL Linux paths

### ISSUE THREAD

**Issue by jxfreeman** [clechasseur/pathcopycopy#47]
You presently support Cygwin paths which prepend the appropriate /cygdrive/**_lower-case-drive-letter_**/.  This can't be replicated using the ECMA/Javascript regular expressions for WSL Linux paths which are also case-sensitive (case sensitivity within WSL can be enabled or disabled through options and file attributes).  However, WSL mounts all mapped drives as /mnt/**_lower-case-drive-letter_**/.   Support for this would make pathing from Windows trivial (convenient).

**Comment by clechasseur** [comment]
This has been implemented in `master` and will be part of the next release.
