### ISSUE TITLE
Suggestion: add \ at a path

### ISSUE THREAD

**Issue by liuzhaoyzz** [clechasseur/pathcopycopy#49]
If copy a path,could you add a \ at the end of path?such as "C:\Windows\System32\“.
If copy a filename,it needn't add a \ at the end.
thank you!

**Comment by clechasseur** [comment]
Not sure where you found it, because as of this writing, 16.0 is not released yet. But it will be soon. :-)

**Comment by liuzhaoyzz** [comment]
I downloaded 16.0 and checked the option add / or \ at the end of the path,but it did not work.What is wrong with me?WIN10X64

**Comment by clechasseur** [comment]
Not sure. I just tried it again and it seems to work...
1. Which option did yoou check? Make sure you check "Append a separator to directory paths" in the "Options" tab.
2. Which command did you try to use?

**Comment by liuzhaoyzz** [comment]
1.I am sure I checked "Append a separator to directory paths" in the "Options" tab.
2.Which command did you try to use?
Right click a directory or right click at the blank area in windows explorer,then click copy file/folder path,paste in the windows notepad or word,the directory without \.
in WIN7X64 Chinese,as below:
![qq 20181201090451](https://user-images.githubusercontent.com/9776716/49322318-763e1d00-f549-11e8-9bd4-5884d1887e11.png)
![qq 20181201090628](https://user-images.githubusercontent.com/9776716/49322325-7fc78500-f549-11e8-96dc-671c2032d62b.png)
![copy file or folder path at the blank area](https://user-images.githubusercontent.com/9776716/49322333-88b85680-f549-11e8-9eeb-c6d4944c4a52.png)
![qq 20181201091349](https://user-images.githubusercontent.com/9776716/49322334-8fdf6480-f549-11e8-92f2-b652b4071ad0.png)

**Comment by clechasseur** [comment]
I can reproduce now. It's a more specific issue. I'll open a new one.

**Comment by selevo** [comment]
> This has been implemented as a new option in `master` and will be part of the next release, tentatively known as 16.0.

gooooood!
