### ISSUE TITLE
Advanced UI for custom commands

### ISSUE THREAD

**Issue by clechasseur** [clechasseur/pathcopycopy#5]
Add an "advanced" mode to custom commands in the Settings application that would give full control over the command's pipeline elements.

Original issue: https://pathcopycopy.codeplex.com/workitem/11389

**Comment by vbNETonIce** [comment]
I'm using zulip/zulip a lot which supports markdown and their desktop app can open file:/// paths.
I would love to have something like a context menu entry `Copy Path Zulip Markdown` or just `Copy Path Markdown`
it would then take the last folder name or the file name and create his

`[`Office`](file:///C:\Program Files\Office)`
`[`winword.exe`](file:///C:\Program Files\Office\winword.exe)`

**Comment by clechasseur** [comment]
@vbNETonIce You can do that with a custom command. Base it on "Copy Long Path", and in the Find/Replace options, select "Use regular expressions" and enter:

Find what: ^(.*)$
Replace with: file:///$1

**Comment by vbNETonIce** [comment]
Thanks for the reply. I'll try that! Is there a way of applying this custom setting to 50+ PC via group policy or copying a settings file. in short: After I add this custom setting where does PathCopyCopy save it?

**Comment by clechasseur** [comment]
It's saved in the registry, in HKEY_CURRENT_USER\Software\clechasseur\PathCopyCopy\PipelinePlugins, but it's identified via a GUID. One thing you can try is to open the Settings app and choose "Export settings", which will export all your settings in a .reg file. Trim it down using a text editor to keep only your plugin and I guess you could apply that across a network by importing the registry file - I'm no expert with group policies but I'm sure there's a way.

**Comment by vbNETonIce** [comment]
one word: sweet! I do a lot of registry modifications via group policy so this should work. Will let you know about the outcome.

**Comment by vbNETonIce** [comment]
ok, worked fine. Things to remember for whoever wants to try it. 
* create all three registry entries
* set the (default) key as default (or standard as in the screenshot). If you forget PCC will report an error as the GPO create two default entries 

I still have a question though: The new custom command can be found in the path copy copy settings but it's not checked as Main. Where is that setting saved?

**Comment by vbNETonIce** [comment]
oh, ok. found it:
`HKEY_CURRENT_USER\Software\clechasseur\PathCopyCopy\MainMenuDisplayOrder`

**Comment by vbNETonIce** [comment]
![5 keys need to be added](https://user-images.githubusercontent.com/26190934/28827266-4fcfacd4-76cd-11e7-95bd-ed990428b7fe.png)
This works great. Thanks for your help. But I assume the GUID will be different for other people.

**Comment by clechasseur** [comment]
The GUIDs of built-in commands (as they appear in `MainMenuDisplayOrder`) will be the same for everyone. However, the GUID of the custom command will be different, yes.

**Comment by clechasseur** [comment]
In hindsight, this issue's original intent seems to complex for little gain. I'll close this for now.

**Comment by clechasseur** [comment]
This has been implemented and merged into `master`. It will be available in the next version (17.0).
