### ISSUE TITLE
Last build doesn't install unless SmartScreen is turned off

### ISSUE THREAD

**Issue by aybe** [clechasseur/pathcopycopy#50]
This was bugging me for quite some time, previous build was working fine.

Currently on `Microsoft Windows [Version 10.0.17134.345]` nothing happens when you click the EXE and you end up with this:

![mmc_2018-11-20_21-59-50](https://user-images.githubusercontent.com/1537591/48802479-aac30500-ed0f-11e8-8ac9-fe0d9698cb3a.png)

![mmc_2018-11-20_22-00-10](https://user-images.githubusercontent.com/1537591/48802478-aac30500-ed0f-11e8-8669-fbbaf03fe0da.png)

After fiddling a bit, turning SmartScreen off allows it to run:

![applicationframehost_2018-11-20_21-58-45](https://user-images.githubusercontent.com/1537591/48802429-8535fb80-ed0f-11e8-9eb3-1dc8e6b429ed.png)

You get the old-school warning:

![explorer_2018-11-20_22-03-41](https://user-images.githubusercontent.com/1537591/48802675-2fae1e80-ed10-11e8-84e4-0394b4fdbc75.png)

But now it starts:

![pathcopycopy15 1 tmp_2018-11-20_22-03-48](https://user-images.githubusercontent.com/1537591/48802676-2fae1e80-ed10-11e8-89af-9284734bc6a3.png)

Not sure if it's related to the wave of buggy patches from Microsoft, e.g. such as I do get my default apps being reset at every boot.

And while Defender reports I'm using Bitdefender Endpoint Security, this setting definitely predates it.

Anyway, that's the fix I found working and wanted to share it with you !

**Comment by clechasseur** [comment]
I basically have this version of Windows too and my SmartScreen option is active, yet I don't experience this. Anyone else had this issue? I'll leave this open.

**Comment by thendarion** [comment]
my AV quarantined the 16.0 installer for no apparent reason on 26th November, and another installer around the same time. so this might not be an issue with the installer but with some random virus definitions in the cloud. :)

**Comment by clechasseur** [comment]
Not sure this was really related to Path Copy Copy - more likely to a bug in Windows itself. I'll close this since no one else seems to be affected.
