### ISSUE TITLE
MSYS/MSYS2 paths

### ISSUE THREAD

**Issue by kbulgrien** [clechasseur/pathcopycopy#51]
MSYS/MSYS2 paths are similar to WSL and Cygwin paths in that they simply drop the leading /mnt or /cygdrive path component respectively, so, with the appearance of these other helpers in PathCopyCopy, it suddenly was very interesting to consider how easily they might be added to this very helpful tool.

WSL example:
  `/mnt/c/msys64/home`

Cygwin:
  `/cygdrive/c/msys64/home`

MSYS/MSYS2:
  `/c/msys64/home`

**Comment by clechasseur** [comment]
This has been implemented in the next version (17.0).
