### ISSUE TITLE
Default command does not add separator at end of path when needed

### ISSUE THREAD

**Issue by clechasseur** [clechasseur/pathcopycopy#52]
The new option to add a separator at end of path for directories does not work for the default command (the one normally added to the main contextual menu). See #49 for investigation.

**Comment by clechasseur** [comment]
This is fixed in the 16.0.1 release.

**Comment by liuzhaoyzz** [comment]
16.0.1 fixed the bug. 
"Append a separator to directory paths" in the "Options" tab worked.
Thank you!
