### ISSUE TITLE
De-HTML/URL-ize paths

### ISSUE THREAD

**Issue by wixoff** [clechasseur/pathcopycopy#53]
Sometimes I end up with filenames that look like "black%20&amp;%20white" and it would be nice to change that to remove the html-specific character encoding.  So here we'd just have "black & white".  Is this doable?

There are online pages to do this.  See: https://www.url-encode-decode.com/

**Comment by clechasseur** [comment]
Just so we're clear, you mean change them when copying the path, right? Wouldn't that produce a path to an invalid file?

**Comment by clechasseur** [comment]
No word on this and I still don't get the point of copying the path to a non-existent file... closing this.

**Comment by wixoff** [comment]
Closing is good.  I thought I had a useful idea but in retrospect it's out-of scope.
