### ISSUE TITLE
"Copy UNC Path" is greyed out

### ISSUE THREAD

**Issue by vanaerde** [clechasseur/pathcopycopy#56]
"Copy UNC Path" and "UNC Parent Folder Path" are greyed out when trying to copy a filename path.

**Comment by clechasseur** [comment]
They are only active when the filename has a network path. Was the file in a network share or network drive?

**Comment by vanaerde** [comment]
Thanks, for network share it is working.

**Comment by Jonathan-LeRoux** [comment]
It used to be (e.g., version 12) that this would work on all files, not only on network shares, and I think it made sense: what if I want to share the absolute path for a file on one machine so that it can be used on another machine?
E.g., my laptop is named "laptop", and I want the path to a file under Downloads.
Long UNC path gives: \\laptop\users\mylogin\Downloads\file.txt
whereas "copy path" gives: C:\users\mylogin\Downloads\file.txt.
With the \\laptop\ path, I can access the file from anywhere on my network if file sharing is setup.
Why not give the option to the user?

**Comment by Jonathan-LeRoux** [comment]
Actually, I take it back regarding versions. It seems to be more a Windows version problem. On Windows 8.1, I get the "Copy Long UNC Path" option available, while it's greyed out on Windows 10, with the same version of Path Copy Copy.
Any idea why?

**Comment by clechasseur** [comment]
Do you try to copy the path of the same directory on both systems? Is one path in a shared folder and the other isn't? If you choose to "Copy Long UNC Path" on your Windows 8.1 system, what do you get in the clipboard?

**Comment by Jonathan-LeRoux** [comment]
I did confirm that on Win 10, the UNC path is available on mapped network drives, but not on local folders, while on Win 8.1 it's available on both.
On 8.1, the clipboard correctly gets \\laptop\users\mylogin\...
I don't have my Win 10 laptop right now but I believe I noticed that even in the settings submenu obtained after right clicking on a local folder, when clicking on UNC path, the example path given is wrong, it shows c:\.... That could be a lead.

**Comment by clechasseur** [comment]
On your 8.1 system, can you open regedit and navigate to the following key:

`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanServer\Shares`

…and check if there is a valid share for your path (users\mylogin\...)?

**Comment by Jonathan-LeRoux** [comment]
Good catch. There is indeed a share for c:\users in my Win 8.1 and Win 7 systems, on which I can get the proper UNC path anywhere under c:\users. I also confirmed that the menu is greyed out for folders outside c:\users, e.g., C:\Program Files, which I hadn't realized until now.
I was actually wondering why file sharing wasn't working properly on my new Win 10 system even after turning file sharing on, and now I understand, the folder itself just wasn't shared...

**Comment by Jonathan-LeRoux** [comment]
By the way, looking at \\localhost is an easy way to check all of this.

**Comment by clechasseur** [comment]
Looks like it is working as intended... Copy UNC Path can only work for file shares and network drive paths.
