### ISSUE TITLE
Change the contextual menu shortcut key "P"

### ISSUE THREAD

**Issue by sibojan9** [clechasseur/pathcopycopy#57]
I have another application that already used P. Is there any way for us to customize the underlined shortcut key?  I am not sure whether or not edits of the Windows registry works.

![snap45](https://user-images.githubusercontent.com/11802171/53681929-4d4f3480-3cbe-11e9-91ad-32e79eefe50b.jpg)

Thanks.

**Comment by clechasseur** [comment]
Unfortunately no, there's no way to customize this right now, even with the registry. It's a rather fringe use case, but I'll see what I can do.

**Comment by clechasseur** [comment]
In the next version (17.0), Path Copy Copy will automatically change the shortcuts of items it adds to the main contextual menu in case of a clash.

**Comment by DamianBISIM** [comment]
What a great feature! 

Using data provided I use the following:
Find what: ^(.*)\\([^\\]+)$
Replace with: $2 "file:///$1\$2"

To get this … (after I press return in MS Word)
PathCopyCopy17.0.1.exe file:///C:\Users\...\Downloads\Path Copy Copy\PathCopyCopy17.0.1.exe

Is there a “Replace with” command where I can get a hyperlink as follows?
PathCopyCopy17.0.1.exe

![PathCopyCopy](https://user-images.githubusercontent.com/55200971/64712021-8c89e980-d488-11e9-8fe9-ee27c86b7e35.png)

**Comment by clechasseur** [comment]
> Using data provided I use the following:

This doesn't seem to have anything to do with this issue. If you have another request or question, please open a new issue; makes it easier to track separate problems. Thank you.
