### ISSUE TITLE
Question: Unattended install

### ISSUE THREAD

**Issue by Styxxy** [clechasseur/pathcopycopy#58]
Hi,
Is it possible to install unattended, and if so, which command line switches can provided to the installer?

(I don't find any docs about this.)

**Comment by blackcrack** [comment]
>"the setup is compiled with Inno Setup and you get all of these for free "
>https://github.com/clechasseur/pathcopycopy/issues/44#issuecomment-431074444
>
>http://www.jrsoftware.org/ishelp/
>/VERYSILENT /CLOSEAPPLICATIONS /NORESTART

**Comment by Styxxy** [comment]
Thanks, exactly what I needed.
