### ISSUE TITLE
Add ability to use username wildcard

### ISSUE THREAD

**Issue by ackwrath** [clechasseur/pathcopycopy#59]
sync onedrive files are stored under the users directory. Enable the ability to swap the currentusername with %USERNAME% to allow links to be sent via msg.

**Comment by clechasseur** [comment]
Sounds like it would be possible to do this with a custom command. Can you give an example of a path, before it would be modified and after (e.g. what you need it to be)?

**Comment by ackwrath** [comment]
Before:
C:\Users\jchow\Company Onedrive Name\Project name

After:
C:\Users\%USERNAME%\Company Onedrive Name\Project name

I would hope you could find the string users\<current environmental variable %USERNAME%> and replace with user\%USERNAME%

**Comment by clechasseur** [comment]
Ok. This would be an enhancement, as from what I understand it's not currently possible to do this.

**Comment by ackwrath** [comment]
no worries. cheers

**Comment by clechasseur** [comment]
This is related to #65.

**Comment by clechasseur** [comment]
In fact, this is a subset of #65. I'll close this one; follow #65 for further development.
