### ISSUE TITLE
Keylock command modifies submenu

### ISSUE THREAD

**Issue by Agivx3** [clechasseur/pathcopycopy#60]
When using keylock command in registry the submenu which you defined before is modified to
suddenly show other entries

**Comment by clechasseur** [comment]
Can you post a screenshot of the menu with and without KeyLock so that we can see the difference?

**Comment by Agivx3** [comment]
Please review the attached screenshots: 1. Settings 2. Without keylock set 3. Keylock set
![Screen1](https://user-images.githubusercontent.com/46596208/54897591-6025e500-4ec9-11e9-99b3-2499a31386fa.jpg)
![Screen2](https://user-images.githubusercontent.com/46596208/54897598-661bc600-4ec9-11e9-9d55-9c890f95528c.jpg)
![Screen3](https://user-images.githubusercontent.com/46596208/54897602-6a47e380-4ec9-11e9-9cd0-fbf37226d037.jpg)

**Comment by clechasseur** [comment]
Hmm. Thanks for the screenshot, I'll look at the code to see what's going on...

**Comment by Agivx3** [comment]
Anything new about this ?

**Comment by clechasseur** [comment]
Ok, sorry it got me so long to get back to this, but I finally took some time to check the code. Basically, this is working as intended.

Path Copy Copy reads settings from registry keys under Software\clechasseur\PathCopyCopy. There's a global copy of this key in HKEY_LOCAL_MACHINE and one for each user in HKEY_CURRENT_USER. Settings in HKCU override those in HKLM.

The KeyLock registry value is a way to lock users out of overriding the global settings. When this is set, the user key is not checked at all - we only use the global key in HKLM.

Thus, what you see is a result of only using the global settings.

If you wanted to see proper settings when using KeyLock, you'd have to configure those settings and then copy them to the registry key in HKEY_LOCAL_MACHINE.

I hope this makes sense, ping here if you need more info. I'll leave this open for a while.
