### ISSUE TITLE
add escaped spaces for WSL paths  (bash style, non-quoted)

### ISSUE THREAD

**Issue by pestrela** [clechasseur/pathcopycopy#61]
The feature to add quotes for directories with spaces works fine - and is required - in WSL. Thank you.
Issue is that that in that case the normal copypath (non-WSL one) also gets quotes, which cannot be used in other file explorer windows.

instead, could you please change WSL to produce always unquoted paths with escaped spaces instead (bash-style?)

thank you again

**Comment by clechasseur** [comment]
This change has been implemented in the next version (17.0).
