### ISSUE TITLE
commands only on submenu

### ISSUE THREAD

**Issue by pestrela** [clechasseur/pathcopycopy#62]
I would live to the option to only have a single submenu with all commands
compare this to the current situation: copy path always in context menu always, plus optional submenu

thank you

**Comment by clechasseur** [comment]
This is already possible. In the Settings, simply uncheck "Main menu" for the Copy Long Path command (and any other command you selected to be in the Main menu) and you'll only get a submenu with the commands you chose.

**Comment by pestrela** [comment]
You are right of course. Thanks again!!
