### ISSUE TITLE
Copy Internet Path with ³

### ISSUE THREAD

**Issue by ststschl** [clechasseur/pathcopycopy#63]
Hello,
most of the directories I'm using Pathcopycopy with are now including a ³. It should probably translate into "%C2%B3" when using the "Copy Internet Path". It currently breaks the link, as it doesn't translate it at all.
Is it possible to get that fixed? 
Cheers,
Stefan.

**Comment by clechasseur** [comment]
During testing for this bug, I found an issue copying Internet Paths that contain spaces. This has been fixed and will be available in the next version (17.0).

However, the ³ character is indeed a valid character in URIs. I've tested it on my machine with a local file containing that character and the copied path works (with the fix above for spaces).
