### ISSUE TITLE
Get rid of .NET Framework 3.5 (2.0 & 3.0) requirement

### ISSUE THREAD

**Issue by detlefs** [clechasseur/pathcopycopy#64]
Would it be a big deal to migrate the tool to run against a newer version of .NET framework, like 4.xx?
The old framework is really outdated by now and for most software it's not required anymore to install it. So, there should be many systems that have not installed .NET 3.5 by default and having it installed just for path-copy-copy seems quite an overhead...

**Comment by clechasseur** [comment]
I've been thinking about it for a while now... as well as dropping Windows XP support. :-)

**Comment by blackcrack** [comment]
hmm.. i hope it works in WinNT Server 2003 because Reactos.org .. :\

**Comment by blackcrack** [comment]
you're welcome ! :100:  :)

**Comment by bexier** [comment]
be nice to get rid of this requirement.  Got to use it just to see my settings?

**Comment by clechasseur** [comment]
@bexier Yes, the requirement is just for the Settings application.

**Comment by clechasseur** [comment]
This change has been implemented. Starting from next version (tentatively known as 17.0), the Settings application will require .NET Framework 4 instead of 2. The installer will no longer attempt to install/enable .NET Framework so for older OSes, the requirement will have to be installed manually.
