### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by Inesicen** [clechasseur/pathcopycopy#65]
How can I copy paths with environment variables like `%PROGRAMFILES(x86)%` and `%USERPROFILE%`?

**Comment by clechasseur** [comment]
I'm not sure I understand. Where exactly would you be copying those paths? Do you mean you want to copy a path and replace part of it with an environment variable?

**Comment by blackcrack** [comment]
@clechasseur 
second ... ![AltText](http://www.blackysgate.de/files/folder-root/smilys/kolobok.us-0/kez_08.gif) 
..... ![AltText](http://www.blackysgate.de/files/folder-root/smilys/kolobok.us-0/kuzya_02.gif) 
open cmd :
echo %PROGRAMFILES(x86)% >> blead.txt , open it with notepad3  and copy it ..
this is a possible way..
but we are not a support forum ..

**Comment by clechasseur** [comment]
Ok… but Path Copy Copy is not used at all in your example… which is basically what prompted my initial question :-)

**Comment by Inesicen** [comment]
If I am copying a path for which an environment variable exists, I would like to be able to copy the path with the variable.

**Comment by clechasseur** [comment]
Interesting idea. But how would be proceed if multiple environment variables exist for the path? Do we go alphabetically?

**Comment by blackcrack** [comment]
humm.. 
"[if included %PROGRAMFILES(x86)% == %PROGRAMFILES(x86)%] copy "%PROGRAMFILES(x86)%/path/blabla, "
else
//path/blabla (or C:\path/blabla) 
"
something in this direction, could be not a bad idea... :) :+1: 
"Copy path with Enviroment Variable" (if variable exist)"

**Comment by clechasseur** [comment]
Looks like this is what we want:

https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-pathunexpandenvstringsw

**Comment by clechasseur** [comment]
This has been implemented as a custom command element in the next major release (tentatively 18.0).

**Comment by Inesicen** [comment]
Thank you; I just note that `%ProgramFiles% (x86)` should be `%ProgramFiles(x86)%`.

**Comment by clechasseur** [comment]
> Thank you; I just note that %ProgramFiles% (x86) should be %ProgramFiles(x86)%.

Is that something from this issue or did you really see this being replaced by the custom command element? If the latter, you can enter a separate bug and I will look at it.
