### ISSUE TITLE
New feature: Paste short name to selected file of parent dir and filename

### ISSUE THREAD

**Issue by stephen147** [clechasseur/pathcopycopy#67]
I know this is against the name of the script but I was wondering if this functionality could be added.

So it, in essence, it pastes what's in the programs memory removing everything except:

## These examples.

`C:\Program Files\Path Copy Copy` names the selected file `Path Copy Copy`

`C:\Program Files\Path Copy Copy\PathCopyCopySettings.exe` names the selected file `PathCopyCopySettings`

EDIT
---

**Scenario 1**
Let us say I copy a path `C:\Program Files\Path Copy Copy`,I select a different file then right click and paste `Path Copy Copy`.

**Scenario 2**
Let us say I copy a filename `this file.txt`, I select a different file then right click and paste `this file` leaving the extension intact.

This program has this functionality but this is much better as it's customisable.

https://www.extrabit.com/copyfilenames

**Example screenshot**
![image](https://user-images.githubusercontent.com/14054664/60006753-f4d6e500-9668-11e9-924d-f20da65f3fbe.png)

**Comment by clechasseur** [comment]
I'm not sure I understand what you mean by "paste" here. Could you explain this? Paste where?

**Comment by stephen147** [comment]
Paste the name to the selected file. See the new examples in OP.

**Comment by clechasseur** [comment]
That's a feature that has little to do with Path Copy Copy's namesake functionality, although I see the link. I'll think it over and leave this open in the meantime.

**Comment by clechasseur** [comment]
I thought about this and I don't think this feature belongs in Path Copy Copy. This extension's goal is to emulate the original Path Copy extension, which copied paths. Pasting them is another thing altogether.

Furthermore, the tool you link to seems to do the job alright - you could install both Path Copy Copy and that other tools, it seems, which would solve your problem.

Closing this. I will only reopen if I get a good PR for this.

**Comment by stephen147** [comment]
Okay no problem, I just thought that copying and pasting filenames were very closely related.
