### ISSUE TITLE
Exporting settings to paths with spaces causes an issue

### ISSUE THREAD

**Issue by stephen147** [clechasseur/pathcopycopy#68]
Saving to this path is fine: `C:\Users\username\Desktop`

Shared folder
Not this: `\\PRINCE_NASEEM\NAS Storage\Apps (Installers)\Windows Tools\Context Menu Apps\PathCopyCopy`

Mapped network drive
Or this:`Z:\Apps (Installers)\Windows Tools\Context Menu Apps\PathCopyCopy`

**Comment by clechasseur** [comment]
Could you describe what the issue is? The file isn't created properly?

**Comment by stephen147** [comment]
It's not created at all.

![image](https://user-images.githubusercontent.com/14054664/60005610-bfc99300-9666-11e9-8685-f267b6d735dc.png)

**Comment by clechasseur** [comment]
Unfortunately no, there isn't any debug file currently... I'll look this up.

**Comment by clechasseur** [comment]
This has been fixed in `master` and will be available in the next version (17.0).

**Comment by stephen147** [comment]
Cheers, look forward to that.
