### ISSUE TITLE
BUG: context appears even when no files are selected

### ISSUE THREAD

**Issue by stephen147** [clechasseur/pathcopycopy#69]
## See attached

![image](https://user-images.githubusercontent.com/14054664/59964634-11eda580-94fb-11e9-87c0-baf94bcdb83e.png)

**Comment by clechasseur** [comment]
Could you be more specific? What is the bug here?

**Comment by stephen147** [comment]
Sorry I went to edit the subject and didn't hit save.

The new title should explain the issue.

**Comment by clechasseur** [comment]
Ok, I understand. This is not a bug - it's working as intended. When you right-click in the background of a Windows Explorer window, you actually get a contextual menu for the directory containing the files you're viewing. (You can try to Copy Long Path if you want, you'll see what you end up with.)
