### ISSUE TITLE
SUGGESTION - Context menu to show previews option like the sub-menu

### ISSUE THREAD

**Issue by stephen147** [clechasseur/pathcopycopy#70]
### Suggestion as per title:
![image](https://user-images.githubusercontent.com/14054664/60084012-a4c25600-972e-11e9-9fc7-4f07b1054eed.png)

### Just like like option
![image](https://user-images.githubusercontent.com/14054664/60084158-e9e68800-972e-11e9-93c7-57cfd14881c2.png)

**Comment by clechasseur** [comment]
I find this a bit confusing myself, but it sure could be done.

**Comment by clechasseur** [comment]
This has been implemented in the next version (17.0).

**Comment by stephen147** [comment]
Thanks very much. I'm sure this will be useful for many.
