### ISSUE TITLE
Settings are getting saved to the program files folder

### ISSUE THREAD

**Issue by stephen147** [clechasseur/pathcopycopy#71]
Should they not get written to the `%appdata%` folder?

**Comment by clechasseur** [comment]
Settings are actually getting saved to the registry, not in any folder. Are you talking about the default save location when exporting settings perhaps?

**Comment by stephen147** [comment]
Oh. I see. I just saw the `PathCopyCopySettings` file in there and thought it was the settings themselves.

Just when I'm here, are there any plans to have a portable version of this?

**Comment by clechasseur** [comment]
There was a portable version at some point and there were too many issues with it so I stopped shipping it... but it is my wish to resurrect it at some point.
