### ISSUE TITLE
Suggestion: Find-Replace (C:) with (/Volumes/Etc/)

### ISSUE THREAD

**Issue by bexier** [clechasseur/pathcopycopy#72]
I share directory paths with mac users quite often from the same volume.  The Internet Path is Almost exactly what I need.  However it would be great if an option existed to swap out mapped drive names with something I deem necessary to alter the path for the benefit of the Mac user.

When Copied (using "Internet Path") - path would turn from:
file://Z:/STUFF/FOLDER/FILE

to

file:///Volumes/Drive/STUFF/FOLDER/FILE

I would tell Find/Replace to look for "Z:" and replace it with "/Volumes/Drive"

**Comment by clechasseur** [comment]
You could create a custom command to do this. Simply choose "Copy Internet Path" as the base command and perform a find/replace of "Z:" for "/Volumes/Drive".
