### ISSUE TITLE
New custom command option: remove file extension

### ISSUE THREAD

**Issue by Jack1789** [clechasseur/pathcopycopy#76]
Hi, it would be useful if an extra base command could be added to your program, one which don't drops the extensions. So, something like this:

"**PATHCO~1.EXE**"
"**PathCopyCopySettings.exe**"

Turns into something like this:

"**PATHCO~1**"
"**PathCopyCopySettings**"

I'm currently using a customized command, which implements an additional regex expression to reach the desired result:

^(.*)\.[^.]*$
$1

But I would like to further customize it, so it replaces every dot it finds with spaces, like this:

"**PathCopyCopySettings.2019.test.exe**"

"**PathCopyCopySettings 2019 test**"

I don't know how to get the right regex for that, but if there were an extra base command which already drops the filenames' extension, I could simply use the "find / replace" option to modify it.

Thanks.

**Comment by clechasseur** [comment]
I don't think a new base command would work because it would essentially mean duplicating something - but a new custom command option makes sense.

**Comment by blackcrack** [comment]
if, then let copy the name like it is, with points and the user can remove the points, because, then stay's original.. "copy the name, without extension"
This let you stay on the way.. if it's take the "originnal.file.name" .ext
or if the name "the orginal file name.ext" so "the orginal file name" 

best regards
blacky

**Comment by clechasseur** [comment]
Thanks for the tips. I won't spawn a command prompt just to extract path without extension however, since it can be done via regex already. And I will take care of supporting forward slashes in paths, yes. :-)

**Comment by clechasseur** [comment]
Implemented in next version (17.0).

**Comment by blackcrack** [comment]
@clechasseur 
i be at moment playing around to make a win7 update dvd,
if you whant a look : http://www.blackysgate.de/files/folder-root/batch-files/

**Comment by Jack1789** [comment]
Hi, I didn't get the "duplicating something" part of your answer, since as far as I know, there is no base commands that do that already present. By the way, would you please tell me what to add to the next regex expression, so it replaces dots with spaces:

**^(.).[^.]$
$1**

So I can just add a new custom command.

Thanks.

**Comment by blackcrack** [comment]
hmm.. and if the user want the point in the name ?
i have a couples file who have a point vor versioning.. filesx.3.2.5.zip 

this removing of the points should be optional... in any case ...

best regards
Blacky

**Comment by blackcrack** [comment]
oh for personal use.. had not seen th whole posts.. my fault..
sorry :) 
the last dot is clear,, infront of the extension ..

best :)

**Comment by clechasseur** [comment]
@Jack1789 Try this:

[Filename.Without.Extension.Or.Dots.zip](https://github.com/clechasseur/pathcopycopy/files/3562954/Filename.Without.Extension.Or.Dots.zip)

It should work as you want. Note however that you will no longer be able to edit the custom command using the Settings application; doing so will break the new find/replace element.

**Comment by Jack1789** [comment]
It works fine, thanks.
