### ISSUE TITLE
Move project to post-WinXP toolset

### ISSUE THREAD

**Issue by clechasseur** [clechasseur/pathcopycopy#83]
Move code project to a post-WinXP toolset (most likely v142) so that we can begin working with more recent APIs.

**Comment by clechasseur** [comment]
Done in `master`. vNext now requires Windows Vista at a minimum.

**Comment by blackcrack** [comment]
gnh.. unusable for Reactos (Win 2013 Server) pity ..

**Comment by clechasseur** [comment]
> gnh.. unusable for Reactos (Win 2013 Server) pity ..

The 17.x release line will still be available for Win XP and thus should work on ReactOS. But we need to move on - Windows XP hasn't been officially supported for a long time now.

**Comment by blackcrack** [comment]
already okey, you're right :)
