### ISSUE TITLE
Feat request. Copy #n paths from first/last

### ISSUE THREAD

**Issue by Corvus71** [clechasseur/pathcopycopy#84]
Suppose I have: \dir1\dir2\dir3\dir4\file1.exe

It would be nice if there was an option to choose copy #n paths from last/first (in the options when adding a new command in simple mode)

e.g.
copy 1 paths from last: (long path)
\dir4\file1.exe
copy 2 paths from last: (long path)
\dir3\dir4\file1.exe
copy 2 paths from first (long parent folder path)
\dir1\dir2\

Background info:
When emailing onedrive links from locally synced files it does not make sense to send the whole folder location since a personal %userprofile% environment variable is in there
c:\user\<userid>\<company name>\dir1\dir2\file1.exe

The <userid> part is different per person so only sending \dir2\file1.exe would be enough for another person to find the file.

**Comment by clechasseur** [comment]
This would be doable via a regular expression, I think, but I like the idea of making it easier to do.

**Comment by clechasseur** [comment]
This has been implemented as a new expert-only custom command element type. It will be available in the next version.
