### ISSUE TITLE
[Feature Request] Add Preview Ability To Expert Mode

### ISSUE THREAD

**Issue by Jack1789** [clechasseur/pathcopycopy#85]
Hi, when I requested the chance of being able to use several "find/replace" instances I didn't thought of its current implementation in v17; simply brilliant. : )

Is there a way you could add a "preview" section for the customized commands? I mean, something like what it is already available for the "regex" expressions testing, but for the rest of elements. Maybe inserting two text boxes in the free space from the right part of the window, one for an optional sample string and other with the result; they should be common for all the applicable elements, and keep updating themselves according to each new addition and/or modification, showing the resultant string right away, or upon request.

This should make quite easier and straightforward the process of testing a new customized command, mostly when it comes to not having to go back and forth the main setting window, besides doing it on a determined test string.

**P.S.** Make expert mode window's remembers its size.

**Comment by clechasseur** [comment]
I like it a lot.

P.S. I added another issue for window size: #86

**Comment by Jack1789** [comment]
Excellent, thanks a lot.

**Comment by clechasseur** [comment]
This has been implemented in `master` and will be part of the 17.1 release.
