### ISSUE TITLE
[Bug Report] Error Messages With Custom Command Creation

### ISSUE THREAD

**Issue by Jack1789** [clechasseur/pathcopycopy#87]
Hi, there is some erratic behavior while creating a new custom command, basically:

If I use the "Expert Mode", add a new "Find / Replace" element using no strings and press the "OK" button, this window appears:

![pathcc1](https://user-images.githubusercontent.com/54497604/64489259-5dc10880-d227-11e9-835e-6a5ec551edcd.jpg)

And if I repeat the above steps but filling only the "Replace with" field, the program's settings window will get frozen, leaving no other option than shutting it down forcibly; besides, system's memory will start getting exhausted a few seconds later:

![pathcc2](https://user-images.githubusercontent.com/54497604/64489417-864a0200-d229-11e9-9810-e5e7a386826f.jpg)

![wmem](https://user-images.githubusercontent.com/54497604/64489632-daee7c80-d22b-11e9-9bfc-de67cb76d16d.jpg)

Under that circumstance, the contextual menu will start being unresponsiveness and I couldn't access the program's settings anymore, without first deleting the faulty rule out of registry. After pressing the "Close program" button from the Windows' message, the memory over consumption ceased.

I'm using an up to date "Windows 8.1 Pro" operative system.

**Comment by clechasseur** [comment]
I can reproduce. That's pretty weird too. Important bug, I'll try to get a fix in as soon as possible.

**Comment by clechasseur** [comment]
Fixed. Will be released in a short while in 17.0.1.

**Comment by Jack1789** [comment]
Thanks once again for your prompt reply. : )
