### ISSUE TITLE
It is possible to replace %20 by space - only at partial string?

### ISSUE THREAD

**Issue by Peter0** [clechasseur/pathcopycopy#89]
I'm using
- base command "Copy internet path"
- RegExp. from « `^file://(.*)/(.*)$` » to « `"$2":file://///$1/$2` »
and no other modifications (even no escape-spaces-to-%20).

Nevertheless spaces are escaped by %20. I always blamed it to using internet path as base command. However, I want escaped spaces on the right side after the colon (and I get them), but I want real space characters on the left between the quotes (and I don't know how to do).

With V17 I hoped to manage this by the pipeline commands, but I don't know how.
Maybe it is possible (even before V17) by a tricky RegExp. The RegExp should do some iterative replacements, but I don't know if it is possible and also not how to express it. Alternatively one could use some conditional clauses (I could live with it if the RegExp would only replace a maximum of e.g. 10 spaces):
From « `^file://(.*)/((.*)(%20(.*)))$` » to « `"$3(?4 $5:)":file://///$1/$2` » to handle one space - more would need some nested conditionals. (Rf. "Boost Replacement String Conditionals" under https://www.regular-expressions.info/replaceconditional.html )
But according to https://www.regular-expressions.info/ the JavaScript implementation doesn't support them.

To come back to the pipeline: It is possible to tear the string apart and handle left and right part by different stages of the pipeline, concatenating them in the end?

I mean: Get « `^file://(.*)/` » on one hand and get  « `/(.*?)$` » on the other hand.
(By « `?` » I mean "laziness", rf. https://www.regular-expressions.info/repeat.html )
Then processing them differently and merging them together again.

Thanks - Peter

**Comment by clechasseur** [comment]
I don't think it's possible to do what you want right now - and barring a way to include scripting in custom commands, I don't really think it will ever be possible… Sorry. I'll leave this open for a while in case I (or anyone else) have an illumination...

**Comment by clechasseur** [comment]
Actually, I thought of a way to add something that would enable this without needing scripting. I'll keep this open.

**Comment by clechasseur** [comment]
The next version of Path Copy Copy will feature new custom command elements to manipulate values on a _stack_ of character strings. This will allow the kind of multi-part manipulation you wanted. As an example, I produced the following custom command that matches your requirements:

[Peter0.zip](https://github.com/clechasseur/pathcopycopy/files/4907740/Peter0.zip)

You can't open it yet until the next version is released; however you could try installing the dev build of that last commit to try it out:

https://github.com/clechasseur/pathcopycopy/actions/runs/165953375

Just know that if you keep the dev build, you will not be noticed when the official version releases. You can download the new version manually when that happens however and it should install fine.
