### ISSUE TITLE
RegEx-Test - dialog box - result is transferred but then ignored

### ISSUE THREAD

**Issue by BaWue** [clechasseur/pathcopycopy#90]
Just discovered another glitch with the RegEx-Testing-dialog box.

Suppose I have a custom command in Expert Mode consisting of two elements:

1. Use Base Command: Copy Long Path
2. Find / Replace Using Regualar Expressions: Regular expression: "a", Replacement expression: "x", Ignore case: yes

![Unbenannt3](https://user-images.githubusercontent.com/55134147/64618196-16ca4300-d3e0-11e9-9fbe-7f99f18ad907.png)

Now I'm not satisfied with this RegEx and click the "Test ..." button bringing up the "Regular Expression Testing" dialog box, and after fiddling around with the RegEx I end up with:
Regular expression: "b"
Replacement expression: "y"
Ignore case: yes

![Unbenannt4](https://user-images.githubusercontent.com/55134147/64618545-bee00c00-d3e0-11e9-823b-7df56c011210.png)

Clicking "OK" in the "Regular Expression Testing" dialog box transfers the Regular expression "b" and the Replacement expression "y" into the "Custom Command (Expert Mode)" dialog box as expected:

![Unbenannt5](https://user-images.githubusercontent.com/55134147/64618843-4e85ba80-d3e1-11e9-9f89-cdf298376da8.png)

Clicking now "OK" in the "Custom Command (Expert Mode)" dialog box and after that "Edit ...", changing to "Expert Mode" and selecting the "Find / Replace Using Regular Expressions" element shows that the old values for Regular expression "a" and Replacement expression "x" are still active and the RegEx-values have not been changed to "b" and "y".

![Unbenannt6](https://user-images.githubusercontent.com/55134147/64619655-b8eb2a80-d3e2-11e9-9277-b2700262b6d8.png)

Running on Windows 10 Enterprise / 64, Version 1709, Build 16299.1268

**Comment by clechasseur** [comment]
Confirmed. I think I know what's going on too.

**Comment by clechasseur** [comment]
Before this is fixed, a workaround is to edit the regex and replacement expressions post-transfer (any edit will do).

**Comment by clechasseur** [comment]
Fixed in `master`, will be part of the next 17.x release.
