### ISSUE TITLE
Upgrade is failing

### ISSUE THREAD

**Issue by teknowledgist** [clechasseur/pathcopycopy#91]
Hi.  The installer is failing (at least sometimes) on upgrade attempts.  It kills explorer as it is supposed to and then hangs for a bit.  In a manual upgrade, it gives an error about needing to stop the processes using PathCopyCopy (although I don't know what those would be if Explorer is down).  In silent mode, it just returns an exit code of '5'.

My testing machine is down at the moment, but this occurred on my personal machine and at least one other.  

Is there any way to upgrade without uninstalling and rebooting first?

Thanks

**Comment by clechasseur** [comment]
I've had problems in the past asking the installer to shut down Explorer… Did you try upgrading but without shutting down Explorer via the installer? You'll have to reboot at the end, but it might work better...

**Comment by clechasseur** [comment]
(For a silent install, you can instruct the installer not to shut down applications by passing `/NOCLOSEAPPLICATIONS`.)

**Comment by blackcrack** [comment]
something named "Unattended Install switches"

for wiki:

><h2>Unattended Install switches</h2>
>if you need switches for Unattended Install this nice Program, try it with these : 
></br>
><b>PathCopyCopy16.0.1.exe /VERYSILENT /CLOSEAPPLICATIONS /NORESTART</b></br>
>At example by WinNT fresh install ..
></br></br>
>and if you want create a silence install script on running User Session : <br/> <b>PathCopyCopyXX.X.X.exe /VERYSILENT /CLOSEAPPLICATIONS /NORESTART /NOCLOSEAPPLICATIONS </b>
><br/><br/>
>This is a Inno Setup Installer, more about can you read here : <br/> 
[Inno Setup Command Line Parameters](http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline)
><br>
><br>


__copy n'past:__
```
<h2>Unattended Install switches</h2>
if you need switches for Unattended Install this nice Program, try it with these : 
</br>
<b>PathCopyCopy16.0.1.exe /VERYSILENT /CLOSEAPPLICATIONS /NORESTART</b></br>
At Example by WinNT fresh install
</br></br>
and if you want create a silence install script on running User Session : <br/> <b>PathCopyCopyXX.X.X.exe /VERYSILENT /CLOSEAPPLICATIONS /NORESTART /NOCLOSEAPPLICATIONS </b>
<br/><br/>
This is a Inno Setup Installer, more about can you read here : <br/> 
[Inno Setup Command Line Parameters](http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline)
<br>
<br>
```


best 
Blacky

**Comment by BaWue** [comment]
The following manual procedure allows to install an update of PathCopyCopy without the necessity of rebooting afterwards:
1. Run the installer until it complains about "Windows-Explorer" needs to be closed
2. Close the Windows-File-Explorer App if it is open
3. Bring up Task Manager using Ctrl+Alt+Del and open the "Processes" tab
4. Locate "Windows-Explorer" under "Background processes", this actually is not the File-Explorer but the Shell itself
5. Right click on it and select "End Task", this actually removes the taskbar, the Start button and the desktop contents for the moment
6. Continue the update installation of PathCopyCopy by clicking "Next"
7. In Task-Manager Select "File" / "Run new task"
8. In the "Open" edit field type "explorer.exe" an hit "OK", this starts the shell again and brings up your taskbar, Start button and desktop contents again.

I am using this on an account with local admin rights (but not the Administrator account itself). Not shure if this also works on an account which is not member of "Administrators".

**Comment by clechasseur** [comment]
> something named "Unattended Install switches"
> for wiki:

Thanks for the input. I indeed have been planning a wiki section on advanced installation options, including command-line parameters. When this happens, you can check it out also to see if I forgot something.

**Comment by clechasseur** [comment]
> The following manual procedure allows to install an update of PathCopyCopy without the necessity of rebooting afterwards:

This indeed works but is a little bit convoluted. The installer's step to shut down and launch apps again afterwards _should_ take care of this, but it seems buggy at the moment... I think I remember reading in Inno Setup's documentation that it uses a Windows API to implement this, so perhaps it's the API that's buggy.

> I am using this on an account with local admin rights (but not the Administrator account itself). Not shure if this also works on an account which is not member of "Administrators".

It should, although you might see elevation prompts.

**Comment by teknowledgist** [comment]
Hi.  Thanks for all the feedback.

Note:  I first tried the [Chocolately package I'm maintaining](https://chocolatey.org/packages/path-copy-copy) which uses the `/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-` switches.  I didn't know about the `/CLOSEAPPLICATIONS` (or `/NOCLOSEAPPLICATIONS`) switch.  I'll have to try that when I get a chance.  I will also try @BaWue 's process but scripted.

@clechasseur Question:  Is the installer using a different method than the `/CLOSEAPPLICATIONS` switch uses?  If not, then that should make no difference, right?

**Comment by clechasseur** [comment]
> @clechasseur Question:  Is the installer using a different method than the /CLOSEAPPLICATIONS switch uses?  If not, then that should make no difference, right?

The installer lets the user decide whether to close applications or not. Not sure what your question mean though - here, we're trying to determine whether NOT closing the applications improves the stability of the update process. If it is determined that closing applications automatically via the installer causes issues, I can turn off this feature when building the installer.

**Comment by clechasseur** [comment]
@teknowledgist did you have the time to test this? Is there a workaround for the upgrade issue? If disabling the closing of external program works, I'd like to implement this officially in 17.x.

**Comment by blackcrack** [comment]
https://github.com/clechasseur/pathcopycopy/issues/25#issuecomment-533418373

**Comment by blackcrack** [comment]
> 
> 
> > @clechasseur Question:  Is the installer using a different method than the /CLOSEAPPLICATIONS switch uses?  If not, then that should make no difference, right?
> 
> The installer lets the user decide whether to close applications or not. Not sure what your question mean though - here, we're trying to determine whether NOT closing the applications improves the stability of the update process. If it is determined that closing applications automatically via the installer causes issues, I can turn off this feature when building the installer.

>>/CLOSEAPPLICATIONS
>>
>>    Instructs Setup to close applications using files that need to be updated by Setup if possible.
>>/NOCLOSEAPPLICATIONS
>>
>>    Prevents Setup from closing applications using files that need to be updated by Setup. If /CLOSEAPPLICATIONS was also used, this command line parameter is ignored.

it's maybe better, i guess there is a "blacklist" of programms where are look for before it install
like explorer-window or totalcommander to close this application for prevent the user to able to show what's happen or so.. (i guess to a "security" thing for programmers and do"
so, if this not need, , turn off..

best 
Blacky

**Comment by clechasseur** [comment]
> it's maybe better, i guess there have a "blacklist" of programs where search for before it install
> like explorer-window or totalcommander to close this application for prevent the user to able to show what's happen or so.. ( i guess to be a "security" thing for programmers and do"
> so, if this not need, .. , turn it off..

It's not a blacklist - there's a Windows API that the installer uses to get a list of running programs that are using any of the artifacts to be installed. That's the list the installer displays, offering you to shut the programs down.

**Comment by blackcrack** [comment]
what i had already seen .. on an other program .. ehh open-shell .. as example :)

**Comment by teknowledgist** [comment]
In various tests with a few different option but **not** the /NOCLOSEAPPLICATIONS, I was not able to find a pattern for when an upgrade failed.  Sometimes it did, and sometimes it didn't.  Sometimes it closed Explorer (or Xplorer2 lite - my other test app) and sometimes it didn't re-open it.  If the machine was rebooted between the older install and the upgrade (as would likely always be the case), it seemed to be more likely to succeed, but not always.

I never had it fail when I used the /NOCLOSEAPPLICATIONS switch.  Often, the new version was working even though it gave a required reboot exit message (using /RESTARTEXITCODE=3010).

IMO, it's better to succeed with the upgrade and give a notice of a need to reboot than fail the upgrade and make the user figure out how to make it work (i.e. uninstall first).  All I would ask is that you return a "standard" reboot required exit code (if that is the case) for silent installs.  

Thanks.

**Comment by clechasseur** [comment]
> IMO, it's better to succeed with the upgrade and give a notice of a need to reboot than fail the upgrade and make the user figure out how to make it work (i.e. uninstall first).  All I would ask is that you return a "standard" reboot required exit code (if that is the case) for silent installs.

I agree. I will thus disable the closing of applications by the installer. (This is the equivalent of always passing `/NOCLOSEAPPLICATIONS` on the command-line.)

As for the return code, I believe the best way to do this is to use `/RESTARTEXITCODE`. Not all users calling setup from the command-line or in other ways would want a non-zero exit code in this case - it could fail scripts unexpectedly, etc. If you need to a standardized exit code, this switch should do it.

**Comment by clechasseur** [comment]
Starting with version 17.1, installer will no longer offer to close and restart applications. (This can be overridden on the command-line if needed.)
