### ISSUE TITLE
Ampersand (&) is not displayed in context menu

### ISSUE THREAD

**Issue by RemboIII** [clechasseur/pathcopycopy#93]
When copying a link that contains an ampersand (&), that character is not displayed in the Explorer context menu. 
When the link is copied to Skype or Outlook, it's displayed correctly and works fine.  

The "RD" in the links in the picture below should say "R&D":
![PathCopyCopy » Ampersand omitted](https://user-images.githubusercontent.com/42135158/65598815-91788e00-df9c-11e9-83b7-d31bd27edc98.png)

**Comment by clechasseur** [comment]
Haha! Amusing bug. In Windows menus, the ampersand character is used to identify character shortcuts and is not displayed. I'll have to see if it's possible to escape it... Nice catch.

**Comment by clechasseur** [comment]
Looking it up, it seems we need to double-up the ampersand (`&&`).

**Comment by clechasseur** [comment]
Fixed in `master`. Will be part of release 17.1.
