### ISSUE TITLE
PathCopyCopy Settings have not been successfully exported

### ISSUE THREAD

**Issue by SidonieNeron** [clechasseur/pathcopycopy#96]
{ Export Settings... (5) can be used to backup the settings of the current user to a file on disk 
This can be useful to transfer settings to a new computer, or for recovery } ?!? 
An error occurred while exporting settings to "Partition:\Folder_Path\Directory\Settings.reg"
 Settings have not been successfully exported
> No Details given Nor Code about this Error (OS :  Windows 7 Home Premium x64)
N.B. Meme comportement sur d'autres ordinateurs Win7 egalement. 
Merci !  Sidonie (09-Nov-2019) 

![Path Copy Copy _ Commands (Export Settings) (191109)](https://user-images.githubusercontent.com/57551499/68522691-b886e700-02e0-11ea-9706-7cac72c26924.png)

![PathCopyCopy (Export Settings to ) (191109)](https://user-images.githubusercontent.com/57551499/68522606-a48eb580-02df-11ea-8b23-d1d36aff0ae3.png) 

![PathCopyCopy (An error occurred while exporting settings) (191109)](https://user-images.githubusercontent.com/57551499/68522602-9b9de400-02df-11ea-9af7-b623f26aeea2.png) 

### 

- __

**Comment by clechasseur** [comment]
Quelle version de Path Copy Copy utilisez-vous? Il y avait un bug avec les chemins contenant des espaces qui a été corrigé dans la version 17.0...

**Comment by SidonieNeron** [comment]
17.1

**Comment by clechasseur** [comment]
Hmm, étrange.

Je vais essayer d'ajouter de l'info quand une erreur se produit pour qu'on ait plus de facilité à diagnostiquer... Je laisse ceci ouvert.

**Comment by SidonieNeron** [comment]
Merci -  Dans l'attente, petit coucou d'un "Maneken Pis" de Pattaya /
Meilleures 73's / ....  .-  VA / (12-Nov-2019)

**Comment by clechasseur** [comment]
Pouvez-vous essayer la version 17.1.1?

https://github.com/clechasseur/pathcopycopy/releases/tag/v17.1.1

Cette version va afficher le code de retour si jamais une erreur se produit. Cela devrait nous donner un coup de pouce pour déterminer quel est votre problème exact.

**Comment by SidonieNeron** [comment]
Merci Cher Charles , 17.1.1, Ca Maaaaaaaarrcheeee  !!!
< Settings have been exported to "D:\Downloads\Copy as Path [PathCopy Copy]
(GitHub)\Settings\PathCopyCopy [Export Sets] (191125).reg".
   To import them back (possibly on another machine), simply double-click
the .reg file in Windows Explorer >

73,s  /  ..._ ._  /  ON5OS .   \   Bonne Annee 2020 !

**Comment by clechasseur** [comment]
Hmm. Je ne comprends pas trop pourquoi - peut-être l'utilisation de `/y`... en tout cas, tant mieux. 😄
