### ISSUE TITLE
Insert seperator

### ISSUE THREAD

**Issue by geochristof** [clechasseur/pathcopycopy#98]
Hi

When copying paths of multiple files on one line I would like to include a seperator between paths.
So instead of:

C:\Users\geoch_000\Pictures\5.jpg C:\Users\geoch_000\Pictures\6.jpg

I would like this:
C:\Users\geoch_000\Pictures\5.jpg;C:\Users\geoch_000\Pictures\6.jpg

So can the setting screen include the option to include a seperator that we could choose?

Thank you
George

**Comment by blackcrack** [comment]
@geochristof 
you should take the picture from explorer and put it into your Posting..
we can not look into your C:\ , this is easy not possible, 
so put the picture into your posting with your mouse and 
then it is storing the picture on github and can let display.. 
if you press the "comment" button. 

On top, left if you edit your posting, 
can you "Preview" your posting and can go back if you press the "Write" Button Tab at top.

please edit your posting again at the 3 points right top at your posting..
best

**Comment by clechasseur** [comment]
In fact, we don't need to have more info, I understand the question.

> So can the setting screen include the option to include a seperator that we could choose?

The Settings application doesn't allow it, but under the hood, the extensions supports that. It should be possible to do it by editing the registry directly using regedit.

Key: HKEY_CURRENT_USER\Software\clechasseur\PathCopyCopy
Value: PathsSeparator

Just create/edit this REG_SZ value and set it to whatever you want, like `;`.

**Comment by geochristof** [comment]
Goodmorning,


Thank you. This solved my problem.


Best regards
George


Στό 25/11/2019 σε 4:53 μμ, Charles Lechasseur <notifications@github.com>
γραφή:
In fact, we don't need to have more info, I understand the question.
So can the setting screen include the option to include a seperator that we
could choose?
The Settings application doesn't allow it, but under the hood, the extensions
supports that. It should be possible to do it by editing the registry directly
using regedit.
Key: HKEY_CURRENT_USER\Software\clechasseur\PathCopyCopy
Value: PathsSeparator
Just create/edit this REG_SZ value and set it to whatever you want, like ;.
