### ISSUE TITLE
[FEATURE] Add way to follow symbolic link

### ISSUE THREAD

**Issue by csm10495** [clechasseur/pathcopycopy#99]
**Is your feature request related to a problem? Please describe.**
I have made a link using ```mklink /d```, and would like an option to get the qualified path (including where the symlink actually points to). UNC path currently resolves via the symlink instead of the location.

**Describe the solution you'd like**
New option to get UNC path (and resolve symlinks)

**Describe alternatives you've considered**
Just using UNC

**Additional context**
Here is an example:

I moved my .minecraft folder from Roaming/ to Y:/.minecraft
Then I did ```mklink /D "Roaming/.minecraft" "Y:/.minecraft"```
If I am in Roaming/.minecraft and click a folder (say Roaming/.minecraft/Folder), I can't come up with a way to get the Y:/.minecraft/Folder path instead of Roaming/.minecraft/Folder.

**Comment by csm10495** [comment]
The feature I'm requesting is similar to this feature of Pathlib in python: https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve

**Comment by csm10495** [comment]
This function seems to auto-resolve the symlinks: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfinalpathnamebyhandlew. I wonder if combining UNC with calling this function would be enough to get it all the time.

**Comment by clechasseur** [comment]
I'll remove "directory" from the title, since this could also apply to file links I think.

**Comment by clechasseur** [comment]
Should be possible to identify a symbolic link through this function:

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileattributesexa

and looking for FILE_ATTRIBUTE_REPARSE_POINT.

**Comment by clechasseur** [comment]
This has been implemented in the `feature/post-winxp` branch and will be part of the next major release (tentatively labeled "18.0").
